<?php

declare(strict_types=1);

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Spatie\Permission\PermissionRegistrar;

/**
 * Seeds the FilamentShield-compatible permissions for the LaraZeus Dynamic
 * Dashboard Layout resource, and attaches them to the super_admin / admin /
 * owner roles so the dashboard builder is accessible out of the box.
 *
 * FilamentShield uses the naming convention:
 *   {action}_{snake_case_resource}
 *
 * The full set generated by `artisan shield:generate --resource=LayoutResource`:
 *   view_any_layout, view_layout, create_layout, update_layout,
 *   delete_layout, delete_any_layout, restore_layout, restore_any_layout,
 *   force_delete_layout, force_delete_any_layout, replicate_layout, reorder_layout
 *
 * Usage:
 *   php artisan db:seed --class=DashboardLayoutPermissionsSeeder
 */
class DashboardLayoutPermissionsSeeder extends Seeder
{
    /** @var list<string> */
    private const LAYOUT_PERMISSIONS = [
        'view_any_layout',
        'view_layout',
        'create_layout',
        'update_layout',
        'delete_layout',
        'delete_any_layout',
        'restore_layout',
        'restore_any_layout',
        'force_delete_layout',
        'force_delete_any_layout',
        'replicate_layout',
        'reorder_layout',
    ];

    public function run(): void
    {
        app()[PermissionRegistrar::class]->forgetCachedPermissions();

        foreach (self::LAYOUT_PERMISSIONS as $permission) {
            Permission::firstOrCreate(
                ['name' => $permission, 'guard_name' => 'web'],
            );
        }

        // Attach all layout permissions to privileged roles
        foreach (['super_admin', 'admin', 'owner'] as $roleName) {
            $role = Role::firstOrCreate(['name' => $roleName, 'guard_name' => 'web']);
            $role->givePermissionTo(self::LAYOUT_PERMISSIONS);
        }

        $this->command->info('✓ Dashboard layout permissions seeded and assigned to super_admin, admin, owner roles.');
    }
}
