<?php

namespace Modules\AIDocument\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use Modules\AIDocument\Entities\AiTemplate;
class AiTemplateTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Model::unguard();
        $templates = [
            ['id' => 1, 'name' => 'Article Generator', 'icon' => 'article-generator.png', 'description' => 'Compose an excellent article using a given title and outline', 'template_code' => 'KPAQQ', 'status' => true, 'professional' => false, 'category_id' =>'1', 'slug' => 'article-generator', 'type' => '1','form_fields'=>'{"field":[{"label":"Article Title","placeholder":"e.g. Amazing  culture of india","field_type":"text_box","field_name":"title"},{"label":"Focus Keywords (comma seperated)","placeholder":"e.g. brazil, canada, india","field_type":"text_box","field_name":"keywords"}]}'],

            ['id' => 2, 'name' => 'Content Rewriter', 'icon' => 'content-rewriter.png', 'description' => 'Enhance content by rewriting it with greater creativity, interest, and engagement', 'template_code' => 'WCZGL', 'status' => true, 'professional' => false, 'category_id' =>'1', 'slug' => 'content-rewriter', 'type' => '1','form_fields'=>'{"field":[{"label":"What would you like to rewrite?","placeholder":"e.g. Enter your text to rewrite","field_type":"textarea","field_name":"title"}]}'],

            ['id' => 3, 'name' => 'Paragraph Generator', 'icon' => 'paragraph-generator.png', 'description' => 'Paragraphs that are flawlessly arranged, simple to read, and packed with words that convince', 'template_code' => 'JXRZB', 'status' => true, 'professional' => false, 'category_id' =>'1', 'slug' => 'paragraph-generator', 'type' => '1' ,'form_fields'=>'{"field":[{"label":"Paragraph Description","placeholder":"e.g. Lime or lemon what is better?","field_type":"textarea","field_name":"title"},{"label":"Focus Keywords (comma seperated)","placeholder":"e.g. fruit, lime","field_type":"text_box","field_name":"keywords"}]}'],

            ['id' => 4, 'name' => 'Talking Points', 'icon' => 'talking-points.png', 'description' => 'Compose concise, straightforward, and informative subheadings for your article', 'template_code' => 'VFWSQ', 'status' => true, 'professional' => false, 'category_id' =>'1', 'slug' => 'talking-points', 'type' => '1','form_fields'=>'{"field":[{"label":"Article Title","placeholder":"e.g. 10 ways to create websites","field_type":"textarea","field_name":"title"},{"label":"Subheading Description","placeholder":"e.g. Why you should create a website","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 5, 'name' => 'Pros & Cons', 'icon' => 'pros-and-cons.png', 'description' => 'Outline the pros and cons of a product, service, or website in your blog post', 'template_code' => 'OPYAB', 'status' => true, 'professional' => false, 'category_id' =>'1', 'slug' => 'pros-and-cons', 'type' => '1','form_fields'=>'{"field":[{"label":"Product Name","placeholder":"e.g. iPhone, Samsung","field_type":"text_box","field_name":"title"},{"label":"Product Description","placeholder":"e.g. Explain what kind of cell phone you can to compare","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 6, 'name' => 'Blog Titles', 'icon' => 'blog-titles.png', 'description' => 'With this tool, you can come up with catchy blog titles that people want to read', 'template_code' => 'WGKYP', 'status' => true, 'professional' => false, 'category_id' =>'2', 'slug' => 'blog-titles', 'type' => '1','form_fields'=>'{"field":[{"label":"What is your blog post is about?","placeholder":"e.g. Describe your blog post","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 7, 'name' => 'Blog Section', 'icon' => 'blog-section.png', 'description' => "Write a few paragraphs about one of your article's subheadings", 'template_code' => 'EEKZF', 'status' => true, 'professional' => false, 'category_id' =>'2', 'slug' => 'blog-section', 'type' => '1','form_fields'=>'{"field":[{"label":"Title of your blog article","placeholder":"e.g. 5 best places to visit in Spain","field_type":"textarea","field_name":"title"},{"label":"Subheadings","placeholder":"e.g. Barcelona, San Sebastian, Madrid","field_type":"textarea","field_name":"subheadings"}]}'],

            ['id' => 8, 'name' => 'Blog Ideas', 'icon' => 'blog-ideas.png', 'description' => 'Article/blog thoughts that you can use to create more traffic, leads, and deals for your business', 'template_code' => 'KDGOX', 'status' => true, 'professional' => false, 'category_id' =>'2', 'slug' => 'blog-ideas', 'type' => '1','form_fields'=>'{"field":[{"label":"What is your blog post is about?","placeholder":"e.g. 5 best places to visit in Spain","field_type":"textarea","field_name":"title"}]}'],

            ['id' => 9, 'name' => 'Blog Intros', 'icon' => 'blog-intros.png', 'description' => 'Introductions to articles/blogs that are appealing to the readers', 'template_code' => 'TZTYR', 'status' => true, 'professional' => false, 'category_id' =>'2', 'slug' => 'blog-intros', 'type' => '1','form_fields'=>'{"field":[{"label":"Blog Post Title","placeholder":"e.g. 5 best places to visit in Spain","field_type":"text_box","field_name":"title"},{"label":"What is your blog post is about?","placeholder":"e.g. describe your blog article","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 10, 'name' => 'Blog Conclusion', 'icon' => 'blog-conclusion.png', 'description' => 'Create powerful conclusion that will make a reader take action.', 'template_code' => 'ZGUKM', 'status' => true, 'professional' => false, 'category_id' =>'2', 'slug' => 'blog-conclusion', 'type' => '1','form_fields'=>'{"field":[{"label":"Blog Post Title","placeholder":"e.g. 5 best places to visit in Spain","field_type":"text_box","field_name":"title"},{"label":"What is your blog post is about?","placeholder":"e.g. describe your blog article","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 11, 'name' => 'Summarize Text', 'icon' => 'summarize-text.png', 'description' => 'Shorten any text into a concise and easily understandable summary', 'template_code' => 'OMMEI', 'status' => true, 'professional' => false, 'category_id' =>'1', 'slug' => 'summarize-text', 'type' => '1','form_fields'=>'{"field":[{"label":"What would you like to summarize?","placeholder":"e.g. Enter your text to summarize","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 12, 'name' => 'Product Description', 'icon' => 'product-description.png', 'description' => 'Craft a compelling product description highlighting its value and why it is worth investing in', 'template_code' => 'HXLNA', 'status' => true, 'professional' => false, 'category_id' =>'1', 'slug' => 'product-description', 'type' => '1','form_fields'=>'{"field":[{"label":"Product name","placeholder":"e.g. VR, Honda","field_type":"text_box","field_name":"title"},{"label":"Audience","placeholder":"e.g. Women, Aliens","field_type":"text_box","field_name":"audience"},{"label":"Product Description","placeholder":"e.g. VR is an innovative device that can allow you to be part of virtual world","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 13, 'name' => 'Startup Name Generator', 'icon' => 'startup-idea.png', 'description' => 'Generate unique, imaginative, and attention-grabbing names for your startup effortlessly and swiftly', 'template_code' => 'DJSVM', 'status' => true, 'professional' => false, 'category_id' =>'1', 'slug' => 'startup-name-generator', 'type' => '1','form_fields'=>'{"field":[{"label":"Seed words","placeholder":"e.g. flow, app, tech","field_type":"text_box","field_name":"keywords"},{"label":"Startup Description","placeholder":"e.g. Explain what your statrup idea is about","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 14, 'name' => 'Product Name Generator', 'icon' => 'product-name-generator.png', 'description' => 'Generate innovative product names using provided word examples', 'template_code' => 'IXKBE', 'status' => true, 'professional' => false, 'category_id' =>'1', 'slug' => 'product-name-generator', 'type' => '1','form_fields'=>'{"field":[{"label":"Seed words","placeholder":"e.g.  fast, healthy, compact","field_type":"text_box","field_name":"keywords"},{"label":"Product Description","placeholder":"e.g. Provide product details","field_type":"textarea","field_name":"description"}]}'],


            ['id' => 15, 'name' => 'Meta Description', 'icon' => 'meta-description.png', 'description' => 'Based on a description, create a meta description optimized for SEO', 'template_code' => 'JCDIK', 'status' => true, 'professional' => false, 'category_id'=> '3', 'slug' => 'meta-description', 'type' => '1','form_fields'=>'{"field":[{"label":"Website Name","placeholder":"e.g. Amazon, Google","field_type":"text_box","field_name":"title"},{"label":"Website Description","placeholder":"e.g. Describe what your website or business do","field_type":"textarea","field_name":"description"},{"label":"Keywords","placeholder":"e.g.  cloud services, databases","field_type":"text_box","field_name":"keywords"}]}'],

            ['id' => 16, 'name' => 'FAQs', 'icon' => 'questions.png', 'description' => 'Make a list of frequently asked questions based on the description of your product', 'template_code' => 'SZAUF', 'status' => true, 'professional' => false, 'category_id' => '3', 'slug' => 'faqs', 'type' => '1','form_fields'=>'{"field":[{"label":"Product Name","placeholder":"e.g. Amazon, Google","field_type":"text_box","field_name":"title"},{"label":"Product Description","placeholder":"e.g. Describe what your website or business do","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 17, 'name' => 'FAQ Answers', 'icon' => 'questions.png', 'description' => 'Create original responses to frequently asked questions (FAQs) about your website or business', 'template_code' => 'BFENK', 'status' => true, 'professional' => false, 'category_id'=> '3', 'slug' => 'faq-answers', 'type' => '1','form_fields'=>'{"field":[{"label":"Product Name","placeholder":"e.g. Amazon, Google","field_type":"text_box","field_name":"title"},{"label":"What is the question you are generating answers for?","placeholder":"e.g. How to use this product?","field_type":"text_box","field_name":"question"},{"label":"Product Description","placeholder":"e.g. Describe what your website or business do","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 18, 'name' => 'Testimonials / Reviews', 'icon' => 'reply-to-review.png', 'description' => 'User testimonials to be used to add social proof to your website', 'template_code' => 'XLGPP', 'status' => true, 'professional' => false, 'category_id'=> '3', 'slug' => 'testimonials', 'type' => '1','form_fields'=>'{"field":[{"label":"Product Name","placeholder":"e.g. Amazon, Google","field_type":"text_box","field_name":"title"},{"label":"Product Description","placeholder":"e.g. Describe what your website or business do","field_type":"textarea","field_name":"description"}]}'],


            ['id' => 19, 'name' => 'Facebook Ads', 'icon' => 'facebook.png', 'description' => 'Compose Facebook promotions that draw in your crowd and convey a high transformation rate', 'template_code' => 'CTMNI', 'status' => true, 'professional' => false, 'category_id' =>'4', 'slug' => 'facebook-ads', 'type' => '1','form_fields'=>'{"field":[{"label":"Product Name","placeholder":"e.g. VR, Toy","field_type":"text_box","field_name":"title"},{"label":"Audience","placeholder":"e.g. Freelances, Developers","field_type":"text_box","field_name":"audience"},{"label":"Product Description","placeholder":"e.g. VR is an innovative device that can allow you to be part of virtual world","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 20, 'name' => 'Video Descriptions', 'icon' => 'video-tags.png', 'description' => 'Create engaging YouTube descriptions to get viewers to your video', 'template_code' => 'ZLKSP', 'status' => true, 'professional' => false, 'category_id' =>'5', 'slug' => 'video-descriptions', 'type' => '1','form_fields'=>'{"field":[{"label":"What is the title of your video?","placeholder":"e.g. start earning money online","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 21, 'name' => 'Video Titles', 'icon' => 'video-tags.png', 'description' => "Create a catchy YouTube video title to grab people's attention", 'template_code' => 'OJIOV', 'status' => true, 'professional' => false, 'category_id' =>'5', 'slug' => 'video-titles', 'type' => '1','form_fields'=>'{"field":[{"label":"What is your video about?","placeholder":"e.g. Provide description of your video, provide as many details as possible","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 22, 'name' => 'Youtube Tags Generator', 'icon' => 'youTube.png', 'description' => 'Create YouTube tags and keywords optimized for SEO for your video', 'template_code' => 'ECNVU', 'status' => true, 'professional' => false, 'category_id' =>'5', 'slug' => 'youtube-tags-generator', 'type' => '1','form_fields'=>'{"field":[{"label":"Enter your video title or keyword","placeholder":"e.g. cloud","field_type":"textarea","field_name":"title"}]}'],


            ['id' => 23, 'name' => 'Instagram Captions', 'icon' => 'instagram.png', 'description' => 'Use eye-catching captions for your Instagram pictures to attract attention', 'template_code' => 'EOASR', 'status' => true, 'professional' => false, 'category_id' =>'4', 'slug' => 'instagram-captions', 'type' => '1','form_fields'=>'{"field":[{"label":"What is your instragram post about?","placeholder":"e.g. start earning money online","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 24, 'name' => 'Instagram Hashtags Generator', 'icon' => 'instagram.png', 'description' => 'Detect the most effective hashtags for your Instagram posts', 'template_code' => 'IEMBM', 'status' => true, 'professional' => false, 'category_id' =>'4', 'slug' => 'instagram-hashtags', 'type' => '1','form_fields'=>'{"field":[{"label":"Enter a keyword","placeholder":"e.g. makeup","field_type":"text_box","field_name":"keywords"}]}'],

            ['id' => 25, 'name' => 'Social Media Post (Personal)', 'icon' => 'social-media-post-personal.png', 'description' => 'Write a personal social media post that can be shared on any platform', 'template_code' => 'CKOHL', 'status' => true, 'professional' => false, 'category_id' =>'4', 'slug' => 'social-post-personal', 'type' => '1' ,'form_fields'=>'{"field":[{"label":"What is this post about?","placeholder":"e.g. I got fluent in Spanish in 1 week","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 26, 'name' => 'Social Media Post (Business)', 'icon' => 'social-media-post-business.png', 'description' => 'Write a post about your company for any social media platform', 'template_code' => 'ABWGU', 'status' => true, 'professional' => false, 'category_id' =>'4', 'slug' => 'social-post-business', 'type' => '1','form_fields'=>'{"field":[{"label":"Company name","placeholder":"e.g. XYZ","field_type":"text_box","field_name":"title"},{"label":"Provide company description","placeholder":"e.g. XYZ is a leading toy making company","field_type":"textarea","field_name":"description"},{"label":"What is the post about?","placeholder":"e.g. we released a new version of kids favorite toy","field_type":"textarea","field_name":"post"}]}'],

            ['id' => 27, 'name' => 'Facebook Headlines', 'icon' => 'facebook.png', 'description' => 'To make your Facebook ads stand out, write headlines that are enticing and convincing', 'template_code' => 'HJYJZ', 'status' => true, 'professional' => false, 'category_id' =>'4', 'slug' => 'facebook-headlines', 'type' => '1','form_fields'=>'{"field":[{"label":"Product name","placeholder":"e.g. VR, Toy","field_type":"text_box","field_name":"title"},{"label":"Audience","placeholder":"e.g. Women, Parents","field_type":"text_box","field_name":"audience"},{"label":"Product Description","placeholder":"e.g. VR is an innovative device that can allow you to be part of virtual world","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 28, 'name' => 'Google Ads Headlines', 'icon' => 'google.png', 'description' => 'Using Google Ads, promote your product with catchy 30-character headlines', 'template_code' => 'SGZTW', 'status' => true, 'professional' => false, 'category_id' =>'4', 'slug' => 'google-headlines', 'type' => '1','form_fields'=>'{"field":[{"label":"Product name","placeholder":"e.g. VR, Toy","field_type":"text_box","field_name":"title"},{"label":"Audience","placeholder":"e.g. Women, Parents","field_type":"text_box","field_name":"audience"},{"label":"Product Description","placeholder":"e.g. VR is an innovative device that can allow you to be part of virtual world","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 29, 'name' => 'Google Ads Description', 'icon' => 'google.png', 'description' => 'Create a Google Ads description that stands out and brings in leads', 'template_code' => 'YQAFG', 'status' => true, 'professional' => false, 'category_id' =>'4', 'slug' => 'google-ads', 'type' => '1','form_fields'=>'{"field":[{"label":"Product name","placeholder":"e.g. VR, Toy","field_type":"text_box","field_name":"title"},{"label":"Audience","placeholder":"e.g. Women, Parents","field_type":"text_box","field_name":"audience"},{"label":"Product Description","placeholder":"e.g. VR is an innovative device that can allow you to be part of virtual world","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 30, 'name' => 'Problem-Agitate-Solution', 'icon' => 'problem-agitate-solution.png', 'description' => 'For your business, develop one of the most efficient copywriting formulas', 'template_code' => 'BGXJE', 'status' => true, 'professional' => false, 'category_id'=> '3', 'slug' => 'problem-agitate-solution', 'type' => '1','form_fields'=>'{"field":[{"label":"Product Name","placeholder":"e.g. VR, Toy","field_type":"text_box","field_name":"title"},{"label":"Audience","placeholder":"e.g. Freelances, Developers","field_type":"text_box","field_name":"audience"},{"label":"Product Description","placeholder":"e.g. VR is an innovative device that can allow you to be part of virtual world","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 31, 'name' => 'Academic Essay', 'icon' => 'academic-essay.png', 'description' => 'Generate well-crafted academic essays for a wide range of subjects in mere seconds', 'template_code' => 'SXQBT', 'status' => true, 'professional' => false, 'category_id' =>'1', 'slug' => 'academic-essay', 'type' => '1','form_fields'=>'{"field":[{"label":"Essay Title","placeholder":"e.g. Amazing cuisine culture of Mexico","field_type":"text_box","field_name":"title"},{"label":"Focus Keywords (comma seperated)","placeholder":"e.g. taco, sangria, paella","field_type":"text_box","field_name":"keywords"}]}'],

            ['id' => 32, 'name' => 'Welcome Email', 'icon' => 'welcome-email.png', 'description' => 'Make welcome emails for your customers', 'template_code' => 'RLXGB', 'status' => true, 'professional' => false, 'category_id' =>'6', 'slug' => 'email-welcome', 'type' => '1','form_fields'=>'{"field":[{"label":"Your Company/Product Name","placeholder":"e.g. Creative Minds","field_type":"text_box","field_name":"title"},{"label":"Describe your product or company","placeholder":"","field_type":"textarea","field_name":"description"},{"label":"Audience","placeholder":"","field_type":"text_box","field_name":"keywords"}]}'],

            ['id' => 33, 'name' => 'Cold Email', 'icon' => 'cold-email.png', 'description' => 'Using AI, create professional cold emails', 'template_code' => 'RDJEZ', 'status' => true, 'professional' => false, 'category_id' =>'6', 'slug' => 'email-cold', 'type' => '1','form_fields'=>'{"field":[{"label":"Your Company/Product Name","placeholder":"e.g. Creative Minds","field_type":"text_box","field_name":"title"},{"label":"Describe your product or company","placeholder":"","field_type":"textarea","field_name":"description"},{"label":"Audience","placeholder":"","field_type":"text_box","field_name":"keywords"}]}'],

            ['id' => 34, 'name' => 'Follow-Up Email', 'icon' => 'follow-up-email.png', 'description' => 'With only a few clicks, you can create a professional email follow-up', 'template_code' => 'XVNNQ', 'status' => true, 'professional' => false, 'category_id' =>'6', 'slug' => 'email-follow-up', 'type' => '1','form_fields'=>'{"field":[{"label":"Your Company/Product Name","placeholder":"e.g. Creative Minds","field_type":"text_box","field_name":"title"},{"label":"Describe your product or company","placeholder":"","field_type":"textarea","field_name":"description"},{"label":"Following up after","placeholder":"","field_type":"text_box","field_name":"event"},{"label":"Audience","placeholder":"","field_type":"text_box","field_name":"keywords"}]}'],

            ['id' => 35, 'name' => 'Creative Stories', 'icon' => 'creative-stories.png', 'description' => 'Utilize AI to generate imaginative stories based on input text', 'template_code' => 'PAKMF', 'status' => true, 'professional' => false, 'category_id' =>'1', 'slug' => 'creative-stories', 'type' => '1','form_fields'=>'{"field":[{"label":"What is your story is about?","placeholder":"Provide as much details as possible for creating a story tale","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 36, 'name' => 'Grammar Checker', 'icon' => 'grammar-checker.png', 'description' => 'Ensure the content is error-free and lacks any mistakes', 'template_code' => 'OORHD', 'status' => true, 'professional' => false, 'category_id' =>'1', 'slug' => 'grammar-checker', 'type' => '1','form_fields'=>'{"field":[{"label":"Include your text here to check","placeholder":"","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 37, 'name' => 'Summarize for 2nd Grader', 'icon' => 'summarize-for-2nd-grader.png', 'description' => 'Simplify complex content into a summary suitable for a 2nd grade child', 'template_code' => 'SGJLU', 'status' => true, 'professional' => false, 'category_id' =>'1', 'slug' => '2nd-grader', 'type' => '1','form_fields'=>'{"field":[{"label":"Include your text to summarize","placeholder":"","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 38, 'name' => 'Video Scripts', 'icon' => 'video-tags.png', 'description' => 'Create scripts for your videos quickly and begin filming', 'template_code' => 'WISHV', 'status' => true, 'professional' => false, 'category_id' =>'5', 'slug' => 'video-scripts', 'type' => '1','form_fields'=>'{"field":[{"label":"What is your video about?","placeholder":"Provide description of what your video is about, provide all details","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 39, 'name' => 'Amazon Product Description', 'icon' => 'amazon.png', 'description' => 'Amazon product descriptions that appear on the first page of search results', 'template_code' => 'WISTT', 'status' => true, 'professional' => false, 'category_id' =>'7', 'slug' => 'amazon-product', 'type' => '1','form_fields'=>'{"field":[{"label":"Product Name","placeholder":"e.g. Amazing cuisine culture of Mexico","field_type":"text_box","field_name":"title"},{"label":"Focus Keywords (comma seperated)","placeholder":"e.g. taco, sangria, paella","field_type":"text_box","field_name":"keywords"}]}'],

            ['id' => 40, 'name' => 'Article Rewriter ', 'icon' => 'article-rewriter.png', 'description' => "Copy an article, paste it in to the program, and with just one click you'll have an entirely different article to read.", 'template_code' => 'ABCDE', 'status' => true, 'professional' => false, 'category_id' =>'1', 'slug' => 'article-rewriter', 'type' => '1','form_fields'=>'{"field":[{"label":"what is your artical about?","placeholder":"what is your artical about?","field_type":"textarea","field_name":"description"},{"label":"Keywords","placeholder":"Keywords","field_type":"text_box","field_name":"keywords"}]}'],

            ['id' => 41, 'name' => 'Content Rephrase ', 'icon' => 'content-rephrase.png', 'description' => "Rewrite your content in a different tone and manner to appeal to diverse readers", 'template_code' => 'ABCDF', 'status' => true, 'professional' => false, 'category_id' =>'1', 'slug' => 'Content-Rephrase', 'type' => '1','form_fields'=>'{"field":[{"label":"What would you like to rewrite?","placeholder":"What would you like to rewrite?","field_type":"textarea","field_name":"description"},{"label":"Keywords","placeholder":"Keywords","field_type":"text_box","field_name":"keywords"}]}'],


            ['id' => 42, 'name' => 'Text Extender', 'icon' => 'text-extender.png', 'description' => "Make shorter sentences more interesting and descriptive", 'template_code' => 'ABCDG', 'status' => true, 'professional' => false, 'category_id' =>'1', 'slug' => 'Text-Extender', 'type' => '1','form_fields'=>'{"field":[{"label":"Description","placeholder":"Describe your content here...","field_type":"textarea","field_name":"description"},{"label":"Keywords","placeholder":"Keywords","field_type":"text_box","field_name":"keywords"}]}'],

            ['id' => 43, 'name' => 'Content Shorten', 'icon' => 'content-shorten.png', 'description' => "To appeal to various readers, condense your content in a distinct tone and manner", 'template_code' => 'ABCDH', 'status' => true, 'professional' => false, 'category_id' =>'1', 'slug' => 'Content-Shorten', 'type' => '1','form_fields'=>'{"field":[{"label":"Content","placeholder":"Describe your content here...","field_type":"textarea","field_name":"description"},{"label":"Keywords","placeholder":"Keywords","field_type":"text_box","field_name":"keywords"}]}'],

            ['id' => 44, 'name' => 'Quora Answers', 'icon' => 'quora-answers.png', 'description' => "Answers to Quora questions that will establish you as an expert", 'template_code' => 'ABCDI', 'status' => true, 'professional' => false, 'category_id' =>'1', 'slug' => 'Quora-Answers', 'type' => '1','form_fields'=>'{"field":[{"label":"Question","placeholder":"Question","field_type":"text_box","field_name":"title"},{"label":"Information","placeholder":"Information","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 45, 'name' => 'Bullet Point Answers', 'icon' => 'bullet-point-answers.png', 'description' => "Precise and detailed bullet points that answer your consumers' questions in a timely and helpful manner.", 'template_code' => 'ABCDJ', 'status' => true, 'professional' => false, 'category_id' =>'1', 'slug' => 'Bullet-Point', 'type' => '1','form_fields'=>'{"field":[{"label":"Question","placeholder":"Question","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 46, 'name' => 'Definition', 'icon' => 'definition.png', 'description' => "A definition for a term, phrase, or acronym that your target customers frequently use", 'template_code' => 'ABCDK', 'status' => true, 'professional' => false, 'category_id' =>'1', 'slug' => 'Definition', 'type' => '1','form_fields'=>'{"field":[{"label":"Keyword","placeholder":"Keyword","field_type":"text_box","field_name":"keyword"}]}'],

            ['id' => 47, 'name' => 'Answers', 'icon' => 'answers.png', 'description' => "Quick, high-quality responses to your audience's questions and concerns", 'template_code' => 'ABCDL', 'status' => true, 'professional' => false, 'category_id' =>'1', 'slug' => 'Definition', 'type' => '1','form_fields'=>'{"field":[{"label":"Question","placeholder":"Question","field_type":"textarea","field_name":"description"}]}'],


            ['id' => 48, 'name' => 'Questions', 'icon' => 'questions.png', 'description' => "A tool for generating polls and inquiries that involve and involve the audience", 'template_code' => 'ABCDM', 'status' => true, 'professional' => false, 'category_id' =>'1', 'slug' => 'Definition', 'type' => '1','form_fields'=>'{"field":[{"label":"Content","placeholder":"Content","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 49, 'name' => 'Passive to Active Voice', 'icon' => 'passive-to-active-voice.png', 'description' => "Simple and easy method for changing passive statements into active sentences", 'template_code' => 'ABCDN', 'status' => true, 'professional' => false, 'category_id' =>'1', 'slug' => 'Definition', 'type' => '1','form_fields'=>'{"field":[{"label":"Content","placeholder":"Content","field_type":"textarea","field_name":"description"}]}'],

             ['id' => 50, 'name' => 'Rewrite With Keywords', 'icon' => 'rewrite-with-keywords.png', 'description' => "Improve your search engine rankings by rewriting your existing content with more keywords", 'template_code' => 'ABCDO', 'status' => true, 'professional' => false, 'category_id' =>'1', 'slug' => 'Definition', 'type' => '1','form_fields'=>'{"field":[{"label":"What would you like to rewrite?","placeholder":"Enter your content to rewrite","field_type":"textarea","field_name":"description"},{"label":"Keywords","placeholder":"e.g lemon,fruit","field_type":"text_box","field_name":"keywords"}]}'],

             ['id' => 51, 'name' => 'Grammar Correction', 'icon' => 'Grammar Correction.png', 'description' => "Check the grammar and correct the sentences with the AI tool", 'template_code' => 'ABCDP', 'status' => true, 'professional' => false, 'category_id' =>'1', 'slug' => 'Definition', 'type' => '1','form_fields'=>'{"field":[{"label":"Text","placeholder":"Enter your content","field_type":"textarea","field_name":"description"}]}'],

             ['id' => 52, 'name' => 'Company Vision', 'icon' => 'company-vision.png', 'description' => "A vision that attracts the right people, clients, and employees.", 'template_code' => 'ABCDQ', 'status' => true, 'professional' => false, 'category_id' =>'1', 'slug' => 'Definition', 'type' => '1','form_fields'=>'{"field":[{"label":"Company Name","placeholder":"Company Name","field_type":"text_box","field_name":"title"},{"label":"Company Information","placeholder":"Company Information","field_type":"textarea","field_name":"description"}]}'],

             ['id' => 53, 'name' => 'Company Mission', 'icon' => 'company-mission.png', 'description' => "a statement of your company's goals and purpose that is both precise and brief", 'template_code' => 'ABCDR', 'status' => true, 'professional' => false, 'category_id' =>'1', 'slug' => 'Definition', 'type' => '1','form_fields'=>'{"field":[{"label":"Company Name","placeholder":"Company Name","field_type":"text_box","field_name":"title"},{"label":"Company Information","placeholder":"Company Information","field_type":"textarea","field_name":"description"}]}'],

             ['id' => 54, 'name' => 'Company Bios', 'icon' => 'company-bios.png', 'description' => "A concise company bio that will assist you in connecting with your intended audience", 'template_code' => 'ABCDS', 'status' => true, 'professional' => false, 'category_id' =>'1', 'slug' => 'Definition', 'type' => '1','form_fields'=>'{"field":[{"label":"Company Name","placeholder":"Company Name","field_type":"text_box","field_name":"title"},{"label":"Company Information","placeholder":"Company Information","field_type":"textarea","field_name":"description"}]}'],

             ['id' => 55, 'name' => 'Emails', 'icon' => 'emails.png', 'description' => "Emails with a polished appearance that helps you engage leads and customers", 'template_code' => 'ABCDT', 'status' => true, 'professional' => false, 'category_id' =>'6', 'slug' => 'Definition', 'type' => '1','form_fields'=>'{"field":[{"label":"Recipient","placeholder":"Recipient","field_type":"text_box","field_name":"recipient"},{"label":"Recipient Position","placeholder":"Recipient Position","field_type":"text_box","field_name":"recipient_position"},{"label":"Description","placeholder":"Description","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 56, 'name' => 'Emails V2', 'icon' => 'emails-v2.png', 'description' => "Better results through personalised email outreach to your target prospects", 'template_code' => 'ABCDU', 'status' => true, 'professional' => false, 'category_id' =>'6', 'slug' => 'Definition', 'type' => '1','form_fields'=>'{"field":[{"label":"From","placeholder":"","field_type":"text_box","field_name":"from"},{"label":"To","placeholder":"","field_type":"text_box","field_name":"to"},{"label":"Goal","placeholder":"","field_type":"text_box","field_name":"goal"},{"label":"Description","placeholder":"Description","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 57, 'name' => 'Email Subject Lines', 'icon' => 'email-subject-lines.png', 'description' => "Effective email subject lines that boost open rates", 'template_code' => 'ABCDU', 'status' => true, 'professional' => false, 'category_id' =>'6', 'slug' => 'Definition', 'type' => '1','form_fields'=>'{"field":[{"label":"Product Name","placeholder":"","field_type":"text_box","field_name":"title"},{"label":"Email Description","placeholder":"","field_type":"textarea","field_name":"description"}]}'],

             ['id' => 58, 'name' => 'Email Content', 'icon' => 'email-content.png', 'description' => "Effective email content for crafting a polished email body", 'template_code' => 'ABCDV', 'status' => true, 'professional' => false, 'category_id' =>'6', 'slug' => 'Definition', 'type' => '1','form_fields'=>'{"field":[{"label":"Email Content Description","placeholder":"","field_type":"textarea","field_name":"description"}]}'],

             ['id' => 59, 'name' => 'Google Ad Titles', 'icon' => 'google.png', 'description' => "Creating advertisements with catchy and distinctive titles that encourage people to click on your ads and make purchases from your website", 'template_code' => 'ABCDW', 'status' => true, 'professional' => false, 'category_id' =>'4', 'slug' => 'Definition', 'type' => '1','form_fields'=>'{"field":[{"label":"Product name","placeholder":"","field_type":"text_box","field_name":"title"},{"label":"Audience","placeholder":"","field_type":"text_box","field_name":"audience"},{"label":"Product Description","placeholder":"Product Description","field_type":"textarea","field_name":"description"}]}'],

             ['id' => 60, 'name' => 'Twitter Tweets', 'icon' => 'twitter.png', 'description' => "Create relevant and trending tweets with AI", 'template_code' => 'ABCDX', 'status' => true, 'professional' => false, 'category_id' =>'6', 'slug' => 'Definition', 'type' => '4','form_fields'=>'{"field":[{"label":"Topic","placeholder":"","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 61, 'name' => 'LinkedIn Posts', 'icon' => 'linkedIn.png', 'description' => "Inspiring posts for LinkedIn that will help you establish authority and trust in your industry", 'template_code' => 'ABCDY', 'status' => true, 'professional' => false, 'category_id' =>'4', 'slug' => 'Definition', 'type' => '4','form_fields'=>'{"field":[{"label":"Topic","placeholder":"","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 62, 'name' => 'App and SMS Notifications', 'icon' => 'app-and-SMS-notifications.png', 'description' => "Notifications that keep users coming back to your apps, websites, and mobile devices for more", 'template_code' => 'ABCDZ', 'status' => true, 'professional' => false, 'category_id' =>'3', 'slug' => 'Definition', 'type' => '4','form_fields'=>'{"field":[{"label":"Description","placeholder":"","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 63, 'name' => 'LinkedIn Ad Descriptions', 'icon' => 'linkedIn.png', 'description' => "Ad descriptions that highlight your product with professionalism and impact", 'template_code' => 'ABCDA', 'status' => true, 'professional' => false, 'category_id' =>'4', 'slug' => 'Definition', 'type' => '4','form_fields'=>'{"field":[{"label":"Product name","placeholder":"e.g. VR, Honda","field_type":"text_box","field_name":"title"},{"label":"Audience","placeholder":"e.g. Women, Aliens","field_type":"text_box","field_name":"audience"},{"label":"Product Description","placeholder":"e.g. VR is an innovative device that can allow you to be part of virtual world","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 64, 'name' => 'LinkedIn Ad Headlines', 'icon' => 'linkedIn.png', 'description' => "High-converting, click-worthy, and attention-grabbing headlines for LinkedIn ads", 'template_code' => 'ABCDB', 'status' => true, 'professional' => false, 'category_id' =>'4', 'slug' => 'Definition', 'type' => '4','form_fields'=>'{"field":[{"label":"Product name","placeholder":"e.g. VR, Honda","field_type":"text_box","field_name":"title"},{"label":"Audience","placeholder":"e.g. Women, Aliens","field_type":"text_box","field_name":"audience"},{"label":"Product Description","placeholder":"e.g. VR is an innovative device that can allow you to be part of virtual world","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 65, 'name' => 'YouTube Outlines', 'icon' => 'youTube.png', 'description' => "Video outlines that are extremely engaging and simple to create", 'template_code' => 'ABCDC', 'status' => true, 'professional' => false, 'category_id' =>'4', 'slug' => 'Definition', 'type' => '4','form_fields'=>'{"field":[{"label":"What is your video about?","placeholder":"","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 66, 'name' => 'Twitter thread', 'icon' => 'twitter.png', 'description' => "Create interesting Twitter threads from a description", 'template_code' => 'ABCDD', 'status' => true, 'professional' => false, 'category_id' =>'4', 'slug' => 'Definition', 'type' => '4','form_fields'=>'{"field":[{"label":"Description","placeholder":"","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 67, 'name' => 'Social post caption', 'icon' => 'social-post-caption.png', 'description' => "Create attention-grabbing captions for social media posts", 'template_code' => 'EBCDA', 'status' => true, 'professional' => false, 'category_id' =>'4', 'slug' => 'Definition', 'type' => '4','form_fields'=>'{"field":[{"label":"Description","placeholder":"","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 68, 'name' => 'you tube intro', 'icon' => 'youTube.png', 'description' => "Make a speedy and infectious short clasp for your YouTube video" , 'template_code'=> 'FBCDA', 'status' => true, 'professional' => false, 'category_id' =>'4', 'slug' => 'Definition', 'type' => '4','form_fields'=>'{"field":[{"label":"Description","placeholder":"","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 69, 'name' => 'Video tags', 'icon' => 'video-tags.png', 'description' => "Based on the title of the video, create video tags for it", 'template_code' => 'GBCDA', 'status' => true, 'professional' => false, 'category_id' =>'4', 'slug' => 'Definition', 'type' => '4','form_fields'=>'{"field":[{"label":"Description","placeholder":"","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 70, 'name' => 'Article outlines', 'icon' => 'article-outlines.png', 'description' => "Decide on the subject of your essay or thesis", 'template_code' => 'HBCDA', 'status' => true, 'professional' => false, 'category_id' =>'4', 'slug' => 'Definition', 'type' => '4','form_fields'=>'{"field":[{"label":"What is your blog is artical? ","placeholder":"","field_type":"text_box","field_name":"title"},{"label":"Description","placeholder":"","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 71, 'name' => 'SEO Meta Tags (Blog Post)', 'icon' => 'meta-description.png', 'description' => "A set of meta titles and meta description tags that are optimized to improve your blog's search engine rankings", 'template_code' => 'IBCDA', 'status' => true, 'professional' => false, 'category_id' =>'4', 'slug' => 'Definition', 'type' => '4','form_fields'=>'{"field":[{"label":"Blog Title","placeholder":"","field_type":"text_box","field_name":"title"},{"label":"Blog Description","placeholder":"","field_type":"textarea","field_name":"description"},{"label":"Search Term","placeholder":"","field_type":"text_box","field_name":"keywords"}]}'],

            ['id' => 72, 'name' => 'SEO Meta Tags (Homepage)', 'icon' => 'meta-description.png', 'description' => "A set of meta titles and meta description tags that are optimized to improve your home page's search rankings", 'template_code' => 'JBCDA', 'status' => true, 'professional' => false, 'category_id' =>'4', 'slug' => 'Definition', 'type' => '4','form_fields'=>'{"field":[{"label":"Website Name","placeholder":"","field_type":"text_box","field_name":"title"},{"label":"Website Description","placeholder":"","field_type":"textarea","field_name":"description"},{"label":"Search Term/Keywords","placeholder":"","field_type":"text_box","field_name":"keywords"}]}'],

            ['id' => 73, 'name' => 'SEO Meta Tags (Product Page)', 'icon' => 'meta-description.png', 'description' => "A set of meta titles and meta description tags that are optimized to improve your product page's search rankings", 'template_code' => 'KBCDA', 'status' => true, 'professional' => false, 'category_id' =>'4', 'slug' => 'Definition', 'type' => '4','form_fields'=>'{"field":[{"label":"Company Name","placeholder":"","field_type":"text_box","field_name":"company_name"},{"label":"Product Name","placeholder":"","field_type":"text_box","field_name":"title"},{"label":"Product/Service Description","placeholder":"","field_type":"textarea","field_name":"description"},{"label":"Search Term/Keywords","placeholder":"","field_type":"text_box","field_name":"keywords"}]}'],

            ['id' => 74, 'name' => 'Amazon Product Titles', 'icon' => 'amazon.png', 'description' => "Titles for your product that will help it stand out from the crowd of competitors", 'template_code' => 'LBCDA', 'status' => true, 'professional' => false, 'category_id' =>'4', 'slug' => 'Definition', 'type' => '4','form_fields'=>'{"field":[{"label":"Product Name","placeholder":"","field_type":"text_box","field_name":"title"},{"label":"Audience","placeholder":"","field_type":"text_box","field_name":"audience"},{"label":"Product Description","placeholder":"","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 75, 'name' => 'Amazon Product Features', 'icon' => 'amazon.png', 'description' => "Benefits and highlights of your items that will make them powerful to customers", 'template_code' => 'MBCDA', 'status' => true, 'professional' => false, 'category_id' =>'4', 'slug' => 'Definition', 'type' => '4','form_fields'=>'{"field":[{"label":"Product Name","placeholder":"","field_type":"text_box","field_name":"title"},{"label":"Audience","placeholder":"","field_type":"text_box","field_name":"audience"},{"label":"Product Description","placeholder":"","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 76, 'name' => 'Advertisement idea', 'icon' => 'advertisement-idea.png', 'description' => "Create imaginative ad descriptions for a service or product", 'template_code' => 'NBCDA', 'status' => true, 'professional' => false, 'category_id' =>'4', 'slug' => 'Definition', 'type' => '4','form_fields'=>'{"field":[{"label":"Product Name","placeholder":"","field_type":"text_box","field_name":"title"},{"label":"Audience","placeholder":"","field_type":"text_box","field_name":"audience"},{"label":"Product Description","placeholder":"","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 77, 'name' => 'Startup Idea', 'icon' => 'startup-idea.png', 'description' => "Obtain thoughts on the subjects you have suggested for business startup ideas", 'template_code' => 'OBCDA', 'status' => true, 'professional' => false, 'category_id' =>'4', 'slug' => 'Definition', 'type' => '4','form_fields'=>'{"field":[{"label":"Description","placeholder":"","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 78, 'name' => 'Job Description Generator', 'icon' => 'Job-description-generator.png', 'description' => "Build up precise and descriptive job descriptions for the job post", 'template_code' => 'PBCDA', 'status' => true, 'professional' => false, 'category_id' =>'4', 'slug' => 'Definition', 'type' => '4','form_fields'=>'{"field":[{"label":"Description","placeholder":"","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 79, 'name' => 'Resume', 'icon' => 'resume.png', 'description' => "Bring a resume with AI that is well-written and strategically organised", 'template_code' => 'QBCDA', 'status' => true, 'professional' => false, 'category_id' =>'4', 'slug' => 'Definition', 'type' => '4','form_fields'=>'{"field":[{"label":"Description","placeholder":"","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 80, 'name' => 'Food Recipe', 'icon' => 'food-recipe.png', 'description' => "In one sitting, get ideas for quick and delicious meal recipes", 'template_code' => 'RBCDA', 'status' => true, 'professional' => false, 'category_id' =>'4', 'slug' => 'Definition', 'type' => '4','form_fields'=>'{"field":[{"label":"Description","placeholder":"","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 81, 'name' => 'Creative poetry', 'icon' => 'creative-poetry.png', 'description' => "Write poetry that expresses your feelings regarding", 'template_code' => 'SBCDA', 'status' => true, 'professional' => false, 'category_id' =>'4', 'slug' => 'Definition', 'type' => '4','form_fields'=>'{"field":[{"label":"Description","placeholder":"","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 82, 'name' => 'Progress Report', 'icon' => 'progress-report.png', 'description' => "Get accurate and comprehensive progress reports for your business", 'template_code' => 'SBCDA', 'status' => true, 'professional' => false, 'category_id' =>'4', 'slug' => 'Definition', 'type' => '4','form_fields'=>'{"field":[{"label":"Description","placeholder":"","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 83, 'name' => 'Fictional Story Idea', 'icon' => 'fictional-story-idea.png', 'description' => "Create fictitious stories with the characters based on the topics you've chosen", 'template_code' => 'SBCDA', 'status' => true, 'professional' => false, 'category_id' =>'4', 'slug' => 'Definition', 'type' => '4','form_fields'=>'{"field":[{"label":"Description","placeholder":"","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 84, 'name' => 'Webinar Title ideas', 'icon' => 'webinar-title-ideas.png', 'description' => "With this tool, you can come up with catchy webinar titles that people want to listen", 'template_code' => 'SBCDA', 'status' => true, 'professional' => false, 'category_id' =>'4', 'slug' => 'Definition', 'type' => '4','form_fields'=>'{"field":[{"label":"Description","placeholder":"","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 85, 'name' => 'Snapchat Ad Title', 'icon' => 'snapcha.png', 'description' => "Creating advertisements with catchy and distinctive titles that encourage people to click on your ads and make purchases from your website", 'template_code' => 'SBCDA', 'status' => true, 'professional' => false, 'category_id' =>'4', 'slug' => 'Definition', 'type' => '4','form_fields'=>'{"field":[{"label":"Product Name","placeholder":"","field_type":"text_box","field_name":"title"},{"label":"Audience","placeholder":"","field_type":"text_box","field_name":"audience"},{"label":" Description","placeholder":"","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 86, 'name' => 'Shopify Product Description', 'icon' => 'shopify.png', 'description' => "Shopify product descriptions that appear on the first page of search results", 'template_code' => 'SBCDA', 'status' => true, 'professional' => false, 'category_id' =>'4', 'slug' => 'Definition', 'type' => '4','form_fields'=>'{"field":[{"label":"Product Name","placeholder":"","field_type":"text_box","field_name":"title"},{"label":"keywords","placeholder":"","field_type":"text_box","field_name":"keywords"}]}'],

            ['id' => 87, 'name' => 'Personal Bio', 'icon' => 'personal-bio.png', 'description' => "A concise personal bio that will assist you in connecting with your intended people", 'template_code' => 'SBCDA', 'status' => true, 'professional' => false, 'category_id' =>'4', 'slug' => 'Definition', 'type' => '4','form_fields'=>'{"field":[{"label":" Description","placeholder":"","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 88, 'name' => 'Pinterest caption', 'icon' => 'pinterest.png', 'description' => "Use eye-catching captions for your Pinterest pictures to attract attention", 'template_code' => 'SBCDA', 'status' => true, 'professional' => false, 'category_id' =>'4', 'slug' => 'Definition', 'type' => '4','form_fields'=>'{"field":[{"label":" Description","placeholder":"","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 89, 'name' => 'Pinterest Pin Title', 'icon' => 'pinterest.png', 'description' => "With this tool, you can come up with catchy pin titles that people want to read", 'template_code' => 'SBCDA', 'status' => true, 'professional' => false, 'category_id' =>'4', 'slug' => 'Definition', 'type' => '4','form_fields'=>'{"field":[{"label":" Description","placeholder":"","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 90, 'name' => 'Pinterest bio', 'icon' => 'pinterest.png', 'description' => "A concise Pinterest bio that will assist you in connecting with your intended followers", 'template_code' => 'SBCDA', 'status' => true, 'professional' => false, 'category_id' =>'4', 'slug' => 'Definition', 'type' => '4','form_fields'=>'{"field":[{"label":" keywords","placeholder":"","field_type":"text_box","field_name":"keywords"}]}'],

            ['id' => 91, 'name' => 'Reply to review', 'icon' => 'reply-to-review.png', 'description' => "Communicate with informative and approachable replies to the reviews", 'template_code' => 'SBCDA', 'status' => true, 'professional' => false, 'category_id' =>'4', 'slug' => 'Definition', 'type' => '4','form_fields'=>'{"field":[{"label":" Description","placeholder":"","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 92, 'name' => 'Slogan Generator', 'icon' => 'slogan-generator.png', 'description' => "Generate clear, concise, and branded slogans with the help of AI", 'template_code' => 'SBCDA', 'status' => true, 'professional' => false, 'category_id' =>'4', 'slug' => 'Definition', 'type' => '4','form_fields'=>'{"field":[{"label":" keywords","placeholder":"","field_type":"text_box","field_name":"keywords"}]}'],

            ['id' => 93, 'name' => 'TikTok Bio', 'icon' => 'tiktok.png', 'description' => "A concise TikTok bio that will assist you in connecting with your followers", 'template_code' => 'SBCDA', 'status' => true, 'professional' => false, 'category_id' =>'4', 'slug' => 'Definition', 'type' => '4','form_fields'=>'{"field":[{"label":" keywords","placeholder":"","field_type":"text_box","field_name":"keywords"}]}'],

            ['id' => 94, 'name' => 'Cover Letter', 'icon' => 'cover-letter.png', 'description' => "Create cover letters that are tailored, confident, and focused", 'template_code' => 'SBCDA', 'status' => true, 'professional' => false, 'category_id' =>'4', 'slug' => 'Definition', 'type' => '4','form_fields'=>'{"field":[{"label":" Description","placeholder":"","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 95, 'name' => 'Presonal Intro', 'icon' => 'presonal-intro.png', 'description' => "Create appealing and concise personal introductions", 'template_code' => 'SBCDA', 'status' => true, 'professional' => false, 'category_id' =>'4', 'slug' => 'Definition', 'type' => '4','form_fields'=>'{"field":[{"label":" Description","placeholder":"","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 96, 'name' => 'Motivational Quote', 'icon' => 'motivational-quote.png', 'description' => "Generate engaging and memorable motivational quotes on various topics", 'template_code' => 'SBCDA', 'status' => true, 'professional' => false, 'category_id' =>'4', 'slug' => 'Definition', 'type' => '4','form_fields'=>'{"field":[{"label":" Description","placeholder":"","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 97, 'name' => 'Motivational Speech', 'icon' => 'motivational-speech.png', 'description' => "Generate engaging and memorable motivational speeches on various topics", 'template_code' => 'SBCDA', 'status' => true, 'professional' => false, 'category_id' =>'4', 'slug' => 'Definition', 'type' => '4','form_fields'=>'{"field":[{"label":" Description","placeholder":"","field_type":"textarea","field_name":"description"}]}'],

            ['id' => 98, 'name' => 'Generate wishes', 'icon' => 'generate-wishes.png', 'description' => "Bring on positive compliments, and felicitations with AI", 'template_code' => 'SBCDA', 'status' => true, 'professional' => false, 'category_id' =>'4', 'slug' => 'Definition', 'type' => '4','form_fields'=>'{"field":[{"label":"Relation for whom?","placeholder":"","field_type":"text_box","field_name":"relation"},{"label":"Occasion","placeholder":"","field_type":"textarea","field_name":"occasion"}]}'],

            ['id' => 99, 'name' => 'Bid on project', 'icon' => 'bid-on-project.png', 'description' => "Quick selection of vendors for subcontracting the project, or products that are required for a project", 'template_code' => 'SBCDA', 'status' => true, 'professional' => false, 'category_id' =>'4', 'slug' => 'Definition', 'type' => '4','form_fields'=>'{"field":[{"label":" Description","placeholder":"","field_type":"textarea","field_name":"description"}]}'],


            ['id' => 100, 'name' => 'SWMS - Working at Heights', 'icon' => 'resume.png', 'description' => "Safe Work Method Statement for working at heights on construction sites.", 'template_code' => 'SWMS_HEIGHTS', 'status' => true, 'professional' => false, 'category_id' =>'8', 'slug' => 'swms-working-at-heights', 'type' => '1','form_fields'=>'{"field":[{"label":"Job Name","placeholder":"e.g. Roofing repair at Lot 12","field_type":"text_box","field_name":"job_name"},{"label":"Site Address","placeholder":"e.g. 123 King St, Melbourne","field_type":"text_box","field_name":"site_address"},{"label":"Task Description","placeholder":"Describe the work at heights","field_type":"textarea","field_name":"task_description"},{"label":"Key Hazards","placeholder":"List main hazards (e.g. falls, weather, edges)","field_type":"textarea","field_name":"hazards"},{"label":"Existing Controls / PPE","placeholder":"Describe existing controls and PPE","field_type":"textarea","field_name":"controls"}]}' ],

            ['id' => 101, 'name' => 'SWMS - Electrical Works', 'icon' => 'resume.png', 'description' => "Safe Work Method Statement for low-voltage electrical work on active sites.", 'template_code' => 'SWMS_ELECTRICAL', 'status' => true, 'professional' => false, 'category_id' =>'9', 'slug' => 'swms-electrical-works', 'type' => '1','form_fields'=>'{"field":[{"label":"Job Name","placeholder":"e.g. Fit-off townhouse 4","field_type":"text_box","field_name":"job_name"},{"label":"Site Address","placeholder":"e.g. 5 Example Rd, Suburb","field_type":"text_box","field_name":"site_address"},{"label":"Task Description","placeholder":"Describe the electrical work","field_type":"textarea","field_name":"task_description"},{"label":"Key Hazards","placeholder":"E.g. live circuits, isolation, confined spaces","field_type":"textarea","field_name":"hazards"},{"label":"Existing Controls / PPE","placeholder":"Lock-out, test-before-touch, PPE etc.","field_type":"textarea","field_name":"controls"}]}' ],

            ['id' => 102, 'name' => 'SWMS - Excavation & Trenching', 'icon' => 'resume.png', 'description' => "Safe Work Method Statement for excavation, trenching and backfilling.", 'template_code' => 'SWMS_EXCAVATION', 'status' => true, 'professional' => false, 'category_id' =>'10', 'slug' => 'swms-excavation-trenching', 'type' => '1','form_fields'=>'{"field":[{"label":"Job Name","placeholder":"e.g. Services trench for Units 1-4","field_type":"text_box","field_name":"job_name"},{"label":"Site Address","placeholder":"e.g. New estate, Stage 3","field_type":"text_box","field_name":"site_address"},{"label":"Task Description","placeholder":"Describe excavation/trenching task","field_type":"textarea","field_name":"task_description"},{"label":"Ground Conditions / Services","placeholder":"E.g. type of soil, known services","field_type":"textarea","field_name":"conditions"},{"label":"Key Hazards & Controls","placeholder":"Collapse, engulfment, plant movement etc.","field_type":"textarea","field_name":"hazards_controls"}]}' ],

            ['id' => 103, 'name' => 'SWMS - Use of Power Tools', 'icon' => 'resume.png', 'description' => "Safe Work Method Statement for common powered hand tools and equipment.", 'template_code' => 'SWMS_POWERTOOLS', 'status' => true, 'professional' => false, 'category_id' =>'8', 'slug' => 'swms-power-tools', 'type' => '1','form_fields'=>'{"field":[{"label":"Job Name","placeholder":"e.g. Framing stage Lot 21","field_type":"text_box","field_name":"job_name"},{"label":"Site Address","placeholder":"Site address","field_type":"text_box","field_name":"site_address"},{"label":"Tools Involved","placeholder":"List main tools (e.g. drop saw, nail gun)","field_type":"textarea","field_name":"tools"},{"label":"Task Description","placeholder":"Describe how tools will be used","field_type":"textarea","field_name":"task_description"},{"label":"Key Hazards & Controls","placeholder":"Kickback, noise, dust, guarding, training etc.","field_type":"textarea","field_name":"hazards_controls"}]}' ],

            ['id' => 104, 'name' => 'Site Safety Briefing', 'icon' => 'resume.png', 'description' => "One-page safety briefing document for toolbox talks and site inductions.", 'template_code' => 'DOC_SITE_BRIEFING', 'status' => true, 'professional' => false, 'category_id' =>'11', 'slug' => 'site-safety-briefing', 'type' => '1','form_fields'=>'{"field":[{"label":"Project / Site Name","placeholder":"e.g. Smith Residence Renovation","field_type":"text_box","field_name":"project_name"},{"label":"Date","placeholder":"Toolbox meeting date","field_type":"text_box","field_name":"date"},{"label":"Attendees / Trades","placeholder":"List attendees","field_type":"textarea","field_name":"attendees"},{"label":"Key Topics","placeholder":"E.g. today's high-risk work, changes on site","field_type":"textarea","field_name":"topics"},{"label":"Actions / Follow-ups","placeholder":"Record any actions or follow-ups","field_type":"textarea","field_name":"actions"}]}' ],

            ['id' => 105, 'name' => 'Client Scope of Works Letter', 'icon' => 'resume.png', 'description' => "Plain-English client letter outlining scope of works, inclusions and exclusions.", 'template_code' => 'DOC_SCOPE_LETTER', 'status' => true, 'professional' => false, 'category_id' =>'11', 'slug' => 'client-scope-of-works-letter', 'type' => '1','form_fields'=>'{"field":[{"label":"Client Name","placeholder":"e.g. John Smith","field_type":"text_box","field_name":"client_name"},{"label":"Project / Site","placeholder":"Project name or address","field_type":"text_box","field_name":"project_name"},{"label":"Scope Summary","placeholder":"Short summary of works","field_type":"textarea","field_name":"scope_summary"},{"label":"Key Inclusions","placeholder":"Dot points of what is included","field_type":"textarea","field_name":"inclusions"},{"label":"Key Exclusions","placeholder":"Dot points of what is excluded","field_type":"textarea","field_name":"exclusions"}]}' ],


            ['id' => 106, 'name' => 'SWMS - Roofing Works', 'icon' => 'resume.png', 'description' => "Safe Work Method Statement for roofing works including metal and tile roofs.", 'template_code' => 'SWMS_ROOFING', 'status' => true, 'professional' => false, 'category_id' =>'12', 'slug' => 'swms-roofing-works', 'type' => '1','form_fields'=>'{"field":[{"label":"Job Name","placeholder":"e.g. Re-roofing unit 3","field_type":"text_box","field_name":"job_name"},{"label":"Site Address","placeholder":"Site address","field_type":"text_box","field_name":"site_address"},{"label":"Roof Type","placeholder":"e.g. metal deck, concrete tile","field_type":"text_box","field_name":"roof_type"},{"label":"Task Description","placeholder":"Describe roofing activities (installation, removal, repairs)","field_type":"textarea","field_name":"task_description"},{"label":"Key Hazards & Controls","placeholder":"E.g. falls, fragile surfaces, weather, lifting, materials handling","field_type":"textarea","field_name":"hazards_controls"}]}' ],

            ['id' => 107, 'name' => 'SWMS - Concreting & Slab Works', 'icon' => 'resume.png', 'description' => "Safe Work Method Statement for concrete pours, slabs and footings.", 'template_code' => 'SWMS_CONCRETE', 'status' => true, 'professional' => false, 'category_id' =>'13', 'slug' => 'swms-concreting-slab', 'type' => '1','form_fields'=>'{"field":[{"label":"Job Name","placeholder":"e.g. House slab Lot 7","field_type":"text_box","field_name":"job_name"},{"label":"Site Address","placeholder":"Site address","field_type":"text_box","field_name":"site_address"},{"label":"Concrete Element","placeholder":"e.g. slab, footing, path","field_type":"text_box","field_name":"element"},{"label":"Task Description","placeholder":"Describe concreting task (formwork, pour, finish)","field_type":"textarea","field_name":"task_description"},{"label":"Key Hazards & Controls","placeholder":"E.g. pump hoses, trip hazards, manual handling, chemical burns, vibration","field_type":"textarea","field_name":"hazards_controls"}]}' ],

            ['id' => 108, 'name' => 'SWMS - Plumbing & Drainage', 'icon' => 'resume.png', 'description' => "Safe Work Method Statement for domestic plumbing and drainage works.", 'template_code' => 'SWMS_PLUMBING', 'status' => true, 'professional' => false, 'category_id' =>'14', 'slug' => 'swms-plumbing-drainage', 'type' => '1','form_fields'=>'{"field":[{"label":"Job Name","placeholder":"e.g. Rough-in bathrooms and kitchen","field_type":"text_box","field_name":"job_name"},{"label":"Site Address","placeholder":"Site address","field_type":"text_box","field_name":"site_address"},{"label":"Task Description","placeholder":"Describe plumbing works (rough-in, fit-off, drainage)","field_type":"textarea","field_name":"task_description"},{"label":"Key Hazards & Controls","placeholder":"E.g. confined spaces, hot works, manual handling, working at heights, sewage exposure","field_type":"textarea","field_name":"hazards_controls"}]}' ],

            ['id' => 109, 'name' => 'SWMS - Carpentry & Framing', 'icon' => 'resume.png', 'description' => "Safe Work Method Statement for timber framing and general carpentry.", 'template_code' => 'SWMS_CARPENTRY', 'status' => true, 'professional' => false, 'category_id' =>'15', 'slug' => 'swms-carpentry-framing', 'type' => '1','form_fields'=>'{"field":[{"label":"Job Name","placeholder":"e.g. Frame stage – single storey dwelling","field_type":"text_box","field_name":"job_name"},{"label":"Site Address","placeholder":"Site address","field_type":"text_box","field_name":"site_address"},{"label":"Task Description","placeholder":"Describe framing/carpentry activities","field_type":"textarea","field_name":"task_description"},{"label":"Key Hazards & Controls","placeholder":"E.g. falls, nail guns, saws, manual handling, noise, dust","field_type":"textarea","field_name":"hazards_controls"}]}' ],

            ['id' => 110, 'name' => 'Site Diary Entry', 'icon' => 'resume.png', 'description' => "Daily site diary entry covering weather, labour, plant and key events.", 'template_code' => 'DOC_SITE_DIARY', 'status' => true, 'professional' => false, 'category_id' =>'11', 'slug' => 'site-diary-entry', 'type' => '1','form_fields'=>'{"field":[{"label":"Project / Site Name","placeholder":"e.g. Brown townhouse development","field_type":"text_box","field_name":"project_name"},{"label":"Date","placeholder":"Diary date","field_type":"text_box","field_name":"date"},{"label":"Weather","placeholder":"Weather conditions","field_type":"text_box","field_name":"weather"},{"label":"Labour & Trades on Site","placeholder":"List trades and numbers","field_type":"textarea","field_name":"labour"},{"label":"Key Activities / Issues","placeholder":"Describe work completed, delays, incidents or issues","field_type":"textarea","field_name":"activities"}]}' ],

            ['id' => 111, 'name' => 'Variation / Change Order Notice', 'icon' => 'resume.png', 'description' => "Formal variation / change order notice to client or builder.", 'template_code' => 'DOC_VARIATION_NOTICE', 'status' => true, 'professional' => false, 'category_id' =>'11', 'slug' => 'variation-change-order-notice', 'type' => '1','form_fields'=>'{"field":[{"label":"Client / Builder Name","placeholder":"e.g. ABC Builders Pty Ltd","field_type":"text_box","field_name":"recipient"},{"label":"Project / Site","placeholder":"Project name or address","field_type":"text_box","field_name":"project_name"},{"label":"Variation Description","placeholder":"Describe the change in scope","field_type":"textarea","field_name":"variation_desc"},{"label":"Reason for Variation","placeholder":"E.g. client request, site condition, design change","field_type":"textarea","field_name":"variation_reason"},{"label":"Cost & Time Impact","placeholder":"Outline cost impact and any extension of time","field_type":"textarea","field_name":"variation_impact"}]}' ],

            ['id' => 112, 'name' => 'Defect / Punch List', 'icon' => 'resume.png', 'description' => "Defect list / punch list for inspections and handover.", 'template_code' => 'DOC_DEFECT_LIST', 'status' => true, 'professional' => false, 'category_id' =>'11', 'slug' => 'defect-punch-list', 'type' => '1','form_fields'=>'{"field":[{"label":"Project / Site Name","placeholder":"e.g. Unit 5 – Final inspection","field_type":"text_box","field_name":"project_name"},{"label":"Date","placeholder":"Inspection date","field_type":"text_box","field_name":"date"},{"label":"Area / Room","placeholder":"E.g. bedroom 1, bathroom","field_type":"text_box","field_name":"area"},{"label":"Defects / Items","placeholder":"List defects or items requiring attention","field_type":"textarea","field_name":"defects"},{"label":"Responsibility / Due Date","placeholder":"Who is responsible and by when","field_type":"textarea","field_name":"responsibility"}]}' ],


            ['id' => 113, 'name' => 'SWMS - Scaffolding & Mobile Towers', 'icon' => 'resume.png', 'description' => "Safe Work Method Statement for fixed scaffolds and mobile scaffold towers.", 'template_code' => 'SWMS_SCAFFOLD', 'status' => true, 'professional' => false, 'category_id' =>'8', 'slug' => 'swms-scaffolding-mobile-towers', 'type' => '1','form_fields'=>'{"field":[{"label":"Job Name","placeholder":"e.g. Scaffold for facade works","field_type":"text_box","field_name":"job_name"},{"label":"Site Address","placeholder":"Site address","field_type":"text_box","field_name":"site_address"},{"label":"Scaffold Type","placeholder":"e.g. fixed, mobile, hanging","field_type":"text_box","field_name":"scaffold_type"},{"label":"Task Description","placeholder":"Describe scaffold erection/modification/dismantle","field_type":"textarea","field_name":"task_description"},{"label":"Key Hazards & Controls","placeholder":"E.g. falls, collapse, overloading, falling objects","field_type":"textarea","field_name":"hazards_controls"}]}' ],

            ['id' => 114, 'name' => 'SWMS - Demolition (Minor / Soft Demo)', 'icon' => 'resume.png', 'description' => "Safe Work Method Statement for minor internal demolition and strip-out works.", 'template_code' => 'SWMS_DEMO_MINOR', 'status' => true, 'professional' => false, 'category_id' =>'10', 'slug' => 'swms-demolition-minor', 'type' => '1','form_fields'=>'{"field":[{"label":"Job Name","placeholder":"e.g. Kitchen and bathroom strip-out","field_type":"text_box","field_name":"job_name"},{"label":"Site Address","placeholder":"Site address","field_type":"text_box","field_name":"site_address"},{"label":"Task Description","placeholder":"Describe demolition/strip-out activities","field_type":"textarea","field_name":"task_description"},{"label":"Existing Structures / Services","placeholder":"Walls, ceilings, services to be isolated","field_type":"textarea","field_name":"existing_structures"},{"label":"Key Hazards & Controls","placeholder":"E.g. falling materials, services, dust, noise, manual handling","field_type":"textarea","field_name":"hazards_controls"}]}' ],

            ['id' => 115, 'name' => 'SWMS - Manual Handling & Materials Handling', 'icon' => 'resume.png', 'description' => "Safe Work Method Statement for manual handling of building materials and use of handling aids.", 'template_code' => 'SWMS_MANUAL_HANDLING', 'status' => true, 'professional' => false, 'category_id' =>'15', 'slug' => 'swms-manual-materials-handling', 'type' => '1','form_fields'=>'{"field":[{"label":"Job Name","placeholder":"e.g. Frame pack and window delivery","field_type":"text_box","field_name":"job_name"},{"label":"Site Address","placeholder":"Site address","field_type":"text_box","field_name":"site_address"},{"label":"Materials / Loads","placeholder":"Describe what is being moved","field_type":"textarea","field_name":"materials"},{"label":"Task Description","placeholder":"Describe how materials are handled, lifted or moved","field_type":"textarea","field_name":"task_description"},{"label":"Key Hazards & Controls","placeholder":"E.g. strain injuries, awkward postures, use of trolleys or lifting aids","field_type":"textarea","field_name":"hazards_controls"}]}' ],

            ['id' => 116, 'name' => 'Pre-Start / Toolbox Talk Record', 'icon' => 'resume.png', 'description' => "Record of daily pre-start or toolbox talk including topics and attendees.", 'template_code' => 'DOC_PRESTART_RECORD', 'status' => true, 'professional' => false, 'category_id' =>'11', 'slug' => 'prestart-toolbox-talk-record', 'type' => '1','form_fields'=>'{"field":[{"label":"Project / Site Name","placeholder":"e.g. Jones Residence Extension","field_type":"text_box","field_name":"project_name"},{"label":"Date","placeholder":"Date of pre-start/toolbox","field_type":"text_box","field_name":"date"},{"label":"Attendees / Trades","placeholder":"List attendees","field_type":"textarea","field_name":"attendees"},{"label":"Key Topics / Hazards","placeholder":"Topics discussed, high-risk work, changes on site","field_type":"textarea","field_name":"topics"},{"label":"Actions / Follow-ups","placeholder":"Agreed actions, person responsible and due date","field_type":"textarea","field_name":"actions"}]}' ],

            ['id' => 117, 'name' => 'Site Induction Checklist', 'icon' => 'resume.png', 'description' => "Checklist for inducting workers and subcontractors onto a site.", 'template_code' => 'DOC_SITE_INDUCTION', 'status' => true, 'professional' => false, 'category_id' =>'11', 'slug' => 'site-induction-checklist', 'type' => '1','form_fields'=>'{"field":[{"label":"Project / Site Name","placeholder":"e.g. New townhouse build","field_type":"text_box","field_name":"project_name"},{"label":"Worker / Company","placeholder":"Name and company of person being inducted","field_type":"text_box","field_name":"worker"},{"label":"Induction Date","placeholder":"Date of induction","field_type":"text_box","field_name":"date"},{"label":"Key Induction Items","placeholder":"Site rules, amenities, emergency info, PPE requirements","field_type":"textarea","field_name":"items"},{"label":"Special Hazards / Notes","placeholder":"Any special hazards or site-specific notes","field_type":"textarea","field_name":"notes"}]}' ],

            ['id' => 118, 'name' => 'Client Quote Cover Letter', 'icon' => 'resume.png', 'description' => "Cover letter to send with a quotation or proposal for building works.", 'template_code' => 'DOC_QUOTE_COVER', 'status' => true, 'professional' => false, 'category_id' =>'11', 'slug' => 'client-quote-cover-letter', 'type' => '1','form_fields'=>'{"field":[{"label":"Client Name","placeholder":"e.g. Sarah and Mark","field_type":"text_box","field_name":"client_name"},{"label":"Project / Site","placeholder":"Project name or address","field_type":"text_box","field_name":"project_name"},{"label":"Summary of Works","placeholder":"Short summary of proposed works","field_type":"textarea","field_name":"summary"},{"label":"Key Inclusions / Highlights","placeholder":"Key selling points or inclusions","field_type":"textarea","field_name":"highlights"},{"label":"Next Steps / Call to Action","placeholder":"Explain how client can accept the quote or ask questions","field_type":"textarea","field_name":"next_steps"}]}' ],

            ['id' => 119, 'name' => 'Practical Completion / Handover Letter', 'icon' => 'resume.png', 'description' => "Letter confirming practical completion and handover of the project.", 'template_code' => 'DOC_PRACTICAL_COMPLETION', 'status' => true, 'professional' => false, 'category_id' =>'11', 'slug' => 'practical-completion-handover-letter', 'type' => '1','form_fields'=>'{"field":[{"label":"Client Name","placeholder":"Client name","field_type":"text_box","field_name":"client_name"},{"label":"Project / Site","placeholder":"Project name or address","field_type":"text_box","field_name":"project_name"},{"label":"Completion Date","placeholder":"Date of practical completion","field_type":"text_box","field_name":"completion_date"},{"label":"Summary of Works Completed","placeholder":"High-level description of what has been delivered","field_type":"textarea","field_name":"summary"},{"label":"Handover Items / Next Steps","placeholder":"Keys, manuals, defect period, contact details, etc.","field_type":"textarea","field_name":"handover_items"}]}' ],

            ['id' => 120, 'name' => 'Non-Conformance Report (NCR)', 'icon' => 'resume.png', 'description' => "Non-conformance report to record issues that deviate from plans, standards or expectations.", 'template_code' => 'DOC_NON_CONFORMANCE_REPORT', 'status' => true, 'professional' => false, 'category_id' =>'11', 'slug' => 'non-conformance-report-ncr', 'type' => '1','form_fields'=>'{"field":[{"label":"Project / Site Name","placeholder":"Project / site","field_type":"text_box","field_name":"project_name"},{"label":"NCR Number","placeholder":"Reference number","field_type":"text_box","field_name":"ncr_number"},{"label":"Description of Non-Conformance","placeholder":"Describe what went wrong or is non-conforming","field_type":"textarea","field_name":"description"},{"label":"Immediate Action / Containment","placeholder":"What was done immediately","field_type":"textarea","field_name":"immediate_action"},{"label":"Corrective Action / Follow-up","placeholder":"Proposed corrective action and responsibilities","field_type":"textarea","field_name":"corrective_action"}]}' ],


            ['id' => 121, 'name' => 'SWMS - Scaffolding & Edge Protection', 'icon' => 'resume.png', 'description' => "Safe Work Method Statement for scaffolding erection, alteration and dismantling, including edge protection.", 'template_code' => 'SWMS_SCAFFOLDING', 'status' => true, 'professional' => false, 'category_id' =>'16', 'slug' => 'swms-scaffolding-edge-protection', 'type' => '1','form_fields'=>'{"field":[{"label":"Job Name","placeholder":"e.g. Scaffold install to townhouse block","field_type":"text_box","field_name":"job_name"},{"label":"Site Address","placeholder":"Site address","field_type":"text_box","field_name":"site_address"},{"label":"Scaffold / Edge Protection Type","placeholder":"e.g. fixed scaffold, mobile tower, guardrails","field_type":"text_box","field_name":"scaffold_type"},{"label":"Task Description","placeholder":"Describe scaffold erection, alteration and dismantling activities","field_type":"textarea","field_name":"task_description"},{"label":"Key Hazards & Controls","placeholder":"E.g. falls, collapse, falling objects, weather, exclusion zones","field_type":"textarea","field_name":"hazards_controls"}]}' ],

            ['id' => 122, 'name' => 'SWMS - Traffic & Pedestrian Management', 'icon' => 'resume.png', 'description' => "Safe Work Method Statement for managing vehicle and pedestrian movements around worksites.", 'template_code' => 'SWMS_TRAFFIC', 'status' => true, 'professional' => false, 'category_id' =>'17', 'slug' => 'swms-traffic-pedestrian-management', 'type' => '1','form_fields'=>'{"field":[{"label":"Job Name","placeholder":"e.g. Road works – lane closure","field_type":"text_box","field_name":"job_name"},{"label":"Site Address / Location","placeholder":"Street or road location","field_type":"text_box","field_name":"site_address"},{"label":"Traffic Conditions","placeholder":"E.g. speed limit, traffic volume, nearby intersections","field_type":"textarea","field_name":"traffic_conditions"},{"label":"Task Description","placeholder":"Describe works affecting traffic/pedestrians","field_type":"textarea","field_name":"task_description"},{"label":"Key Hazards & Controls","placeholder":"E.g. vehicle strikes, signage, traffic controllers, barricades, lighting","field_type":"textarea","field_name":"hazards_controls"}]}' ],

            ['id' => 123, 'name' => 'SWMS - Confined Space Entry', 'icon' => 'resume.png', 'description' => "Safe Work Method Statement for entry into confined spaces such as tanks, pits and shafts.", 'template_code' => 'SWMS_CONFINED_SPACE', 'status' => true, 'professional' => false, 'category_id' =>'18', 'slug' => 'swms-confined-space-entry', 'type' => '1','form_fields'=>'{"field":[{"label":"Job Name","placeholder":"e.g. Pump pit maintenance","field_type":"text_box","field_name":"job_name"},{"label":"Site Address","placeholder":"Site address","field_type":"text_box","field_name":"site_address"},{"label":"Confined Space Description","placeholder":"Describe the space (e.g. pit, tank, manhole)","field_type":"textarea","field_name":"space_description"},{"label":"Key Hazards & Controls","placeholder":"E.g. atmospheric hazards, engulfment, access, permits, standby person","field_type":"textarea","field_name":"hazards_controls"},{"label":"Rescue / Emergency Plan","placeholder":"Outline rescue arrangements and emergency plan","field_type":"textarea","field_name":"rescue_plan"}]}' ],

            ['id' => 124, 'name' => 'SWMS - Demolition & Strip-out', 'icon' => 'resume.png', 'description' => "Safe Work Method Statement for minor demolition, strip-out and removal works.", 'template_code' => 'SWMS_DEMOLITION', 'status' => true, 'professional' => false, 'category_id' =>'19', 'slug' => 'swms-demolition-stripout', 'type' => '1','form_fields'=>'{"field":[{"label":"Job Name","placeholder":"e.g. Internal strip-out – shop fitout","field_type":"text_box","field_name":"job_name"},{"label":"Site Address","placeholder":"Site address","field_type":"text_box","field_name":"site_address"},{"label":"Structure / Area Description","placeholder":"Describe the area or elements being demolished","field_type":"textarea","field_name":"structure_description"},{"label":"Task Description","placeholder":"Describe demolition and removal activities","field_type":"textarea","field_name":"task_description"},{"label":"Key Hazards & Controls","placeholder":"E.g. falling materials, services isolation, dust, noise, manual handling","field_type":"textarea","field_name":"hazards_controls"}]}' ],

            ['id' => 125, 'name' => 'Quality Inspection Checklist', 'icon' => 'resume.png', 'description' => "A quality inspection checklist for recording items inspected, defects and follow-up actions.", 'template_code' => 'DOC_QUALITY_CHECKLIST', 'status' => true, 'professional' => false, 'category_id' =>'11', 'slug' => 'quality-inspection-checklist', 'type' => '1','form_fields'=>'{"field":[{"label":"Project / Site Name","placeholder":"e.g. Apartment build – Level 3","field_type":"text_box","field_name":"project_name"},{"label":"Date","placeholder":"Inspection date","field_type":"text_box","field_name":"date"},{"label":"Area / Location","placeholder":"E.g. unit number or area","field_type":"text_box","field_name":"area"},{"label":"Inspection Items / Observations","placeholder":"List items inspected and any observations","field_type":"textarea","field_name":"items"},{"label":"Actions / Follow-up","placeholder":"Record actions, responsible person and due dates","field_type":"textarea","field_name":"actions"}]}' ],

            ['id' => 126, 'name' => 'Pre-Start Meeting Agenda', 'icon' => 'resume.png', 'description' => "Agenda for a pre-start or pre-construction meeting, covering scope, risks and responsibilities.", 'template_code' => 'DOC_PRESTART_AGENDA', 'status' => true, 'professional' => false, 'category_id' =>'11', 'slug' => 'prestart-meeting-agenda', 'type' => '1','form_fields'=>'{"field":[{"label":"Project / Site Name","placeholder":"e.g. New dwelling – Lot 4","field_type":"text_box","field_name":"project_name"},{"label":"Meeting Date","placeholder":"Meeting date","field_type":"text_box","field_name":"date"},{"label":"Attendees","placeholder":"List key attendees and roles","field_type":"textarea","field_name":"attendees"},{"label":"Key Agenda Items","placeholder":"E.g. scope, programme, high-risk work, responsibilities","field_type":"textarea","field_name":"agenda_items"},{"label":"Actions / Decisions","placeholder":"Record key actions and decisions","field_type":"textarea","field_name":"actions"}]}' ],

        ];

        foreach ($templates as $template) {
            AiTemplate::updateOrCreate(['id' => $template['id']], $template);
        }
        // $this->call("OthersTableSeeder");
    }
}
