<?php

return [
    'payroll_runs' => true,
    'payroll_preview' => true,
    'approval_workflow' => true,
    'variance_checks' => true,
    'ai_anomaly_detection' => true,
    'forecasting' => true,
    'rest_api' => true,
    'graphql_api' => false,
    'bank_export' => true,
    'adjustment_imports' => true,
    'audit_timeline' => true,
    'health_checks' => true,
    'approval_notifications' => true,
    'send_payslips_to_employees' => env('PAYROLL_SEND_PAYSLIPS_TO_EMPLOYEES', true),
    'queue_payslip_delivery' => env('PAYROLL_QUEUE_PAYSLIP_DELIVERY', true),
    'persist_payslip_delivery_audit' => env('PAYROLL_PERSIST_PAYSLIP_DELIVERY_AUDIT', true),
    'secure_payslip_links' => env('PAYROLL_SECURE_PAYSLIP_LINKS', true),
    'employee_payslip_acknowledgements' => env('PAYROLL_EMPLOYEE_PAYSLIP_ACKNOWLEDGEMENTS', true),
    'period_locking' => env('PAYROLL_PERIOD_LOCKING', true),
    'accounting_journal_exports' => env('PAYROLL_ACCOUNTING_JOURNAL_EXPORTS', true),
    'variance_threshold_percent' => env('PAYROLL_VARIANCE_THRESHOLD_PERCENT', 10),
    'prevent_duplicate_runs' => env('PAYROLL_PREVENT_DUPLICATE_RUNS', true),
    'require_guard_before_finalization' => env('PAYROLL_REQUIRE_GUARD_BEFORE_FINALIZATION', true),
    'ess_token_ttl_minutes' => env('PAYROLL_ESS_TOKEN_TTL_MINUTES', 60),
    'delivery_retry_batch_size' => env('PAYROLL_DELIVERY_RETRY_BATCH_SIZE', 50),
];
