<?php

namespace App\Support\TitanOS\Contracts;

/**
 * Modules can implement this interface to supply their own widget schemas
 * to the Titan OS generated UI renderer.  The titanOsWidgets method should
 * return an array of widget definitions that conform to the schema
 * understood by the WidgetRenderer.  These widgets will be merged with
 * those generated by Titan Zero.
 */
interface ProvidesTitanOsWidgets
{
    /**
     * Return an array of widget schemas provided by the module.
     *
     * @return array<int, array<string, mixed>>
     */
    public static function titanOsWidgets(): array;
}