-- Titan Time Engine Pass 5-6 SQL-first install

CREATE TABLE IF NOT EXISTS `tz_calendar_events` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `team_id` BIGINT UNSIGNED NOT NULL,
  `company_id` BIGINT UNSIGNED DEFAULT NULL,
  `user_id` BIGINT UNSIGNED DEFAULT NULL,
  `created_by_team_id` BIGINT UNSIGNED DEFAULT NULL,
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `event_type` VARCHAR(80) DEFAULT 'event',
  `status` VARCHAR(50) DEFAULT 'active',
  `source_type` VARCHAR(80) DEFAULT 'manual',
  `source_id` BIGINT UNSIGNED DEFAULT NULL,
  `owner_type` VARCHAR(120) DEFAULT NULL,
  `owner_id` BIGINT UNSIGNED DEFAULT NULL,
  `starts_at` DATETIME NOT NULL,
  `ends_at` DATETIME NULL,
  `all_day` TINYINT(1) DEFAULT 0,
  `timezone` VARCHAR(64) DEFAULT 'Australia/Melbourne',
  `color` VARCHAR(20) DEFAULT NULL,
  `location` VARCHAR(255) DEFAULT NULL,
  `external_uid` VARCHAR(191) DEFAULT NULL,
  `sync_state` VARCHAR(50) DEFAULT NULL,
  `meta_json` JSON NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_tz_calendar_events_team_start` (`team_id`,`starts_at`),
  KEY `idx_tz_calendar_events_source` (`source_type`,`source_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tz_calendar_recurrence_rules` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `team_id` BIGINT UNSIGNED NOT NULL,
  `company_id` BIGINT UNSIGNED DEFAULT NULL,
  `user_id` BIGINT UNSIGNED DEFAULT NULL,
  `created_by_team_id` BIGINT UNSIGNED DEFAULT NULL,
  `calendar_event_id` BIGINT UNSIGNED NOT NULL,
  `frequency` VARCHAR(20) NOT NULL,
  `interval_value` INT UNSIGNED NOT NULL DEFAULT 1,
  `days_of_week` JSON NULL,
  `until_at` DATETIME NULL,
  `occurrence_limit` INT UNSIGNED NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_tz_calendar_recurrence_event` (`calendar_event_id`),
  KEY `idx_tz_calendar_recurrence_team_active` (`team_id`,`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tz_calendar_sync_accounts` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `team_id` BIGINT UNSIGNED NOT NULL,
  `company_id` BIGINT UNSIGNED DEFAULT NULL,
  `user_id` BIGINT UNSIGNED DEFAULT NULL,
  `created_by_team_id` BIGINT UNSIGNED DEFAULT NULL,
  `provider` VARCHAR(50) NOT NULL,
  `account_name` VARCHAR(150) NOT NULL,
  `calendar_id` VARCHAR(191) DEFAULT NULL,
  `credentials_path` VARCHAR(255) DEFAULT NULL,
  `token_json` JSON NULL,
  `sync_mode` VARCHAR(40) DEFAULT 'push_pull',
  `is_active` TINYINT(1) DEFAULT 1,
  `last_synced_at` DATETIME NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_tz_calendar_sync_accounts_team_active` (`team_id`,`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tz_calendar_sync_links` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `team_id` BIGINT UNSIGNED NOT NULL,
  `company_id` BIGINT UNSIGNED DEFAULT NULL,
  `user_id` BIGINT UNSIGNED DEFAULT NULL,
  `created_by_team_id` BIGINT UNSIGNED DEFAULT NULL,
  `calendar_event_id` BIGINT UNSIGNED NOT NULL,
  `provider` VARCHAR(50) NOT NULL,
  `sync_account_id` BIGINT UNSIGNED DEFAULT NULL,
  `external_event_id` VARCHAR(191) DEFAULT NULL,
  `external_uid` VARCHAR(191) DEFAULT NULL,
  `sync_hash` VARCHAR(191) DEFAULT NULL,
  `last_push_at` DATETIME NULL,
  `last_pull_at` DATETIME NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_tz_calendar_sync_links_team_event` (`team_id`,`calendar_event_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tz_scheduled_tasks` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `team_id` BIGINT UNSIGNED NOT NULL,
  `company_id` BIGINT UNSIGNED DEFAULT NULL,
  `user_id` BIGINT UNSIGNED DEFAULT NULL,
  `created_by_team_id` BIGINT UNSIGNED DEFAULT NULL,
  `task_type` VARCHAR(100) NOT NULL,
  `handler` VARCHAR(180) DEFAULT NULL,
  `status` VARCHAR(50) DEFAULT 'pending',
  `priority` INT DEFAULT 0,
  `scheduled_for` DATETIME NOT NULL,
  `next_run_at` DATETIME NULL,
  `last_run_at` DATETIME NULL,
  `executed_at` DATETIME NULL,
  `failed_at` DATETIME NULL,
  `retry_count` INT DEFAULT 0,
  `max_retries` INT DEFAULT 3,
  `related_type` VARCHAR(120) DEFAULT NULL,
  `related_id` BIGINT UNSIGNED DEFAULT NULL,
  `payload_json` JSON NULL,
  `result_json` JSON NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_tz_scheduled_tasks_team_status_run` (`team_id`,`status`,`scheduled_for`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
