<?php

/*
|--------------------------------------------------------------------------
| Titan OS App Registry
|--------------------------------------------------------------------------
| This registry intentionally exposes curated OS apps, not every Filament
| panel. Future modules can register here when ready.  Each entry should
| define a stable `key`, human‑friendly `name`, short `label`, underlying
| `panel` id, base `route`, `icon` slug, logical `category`, and state
| flags.  Unfinished modules can be marked with `coming_soon` and disabled.
*/

return [
    [
        'key' => 'titan-zero',
        'name' => 'Titan Zero',
        'label' => 'AI Automation',
        'panel' => 'titanzero',
        'route' => '/titanzero',
        'icon' => 'cpu',
        'category' => 'core',
        'enabled' => true,
        'locked' => false,
        'upgrade_required' => false,
        'coming_soon' => false,
        'beta' => false,
        'hidden' => false,
        'disabled' => false,
    ],
    // Additional first‑party panels.  These entries pre‑populate the launcher
    // so users see the full OS landscape from day one.  Note: panels
    // representing unfinished modules are flagged as coming_soon and disabled.
    [
        'key' => 'admin',
        'name' => 'Admin',
        'label' => 'Super Admin',
        'panel' => 'admin',
        'route' => '/admin',
        'icon' => 'shield',
        'category' => 'core',
        'enabled' => true,
        'locked' => false,
        'upgrade_required' => false,
        'coming_soon' => false,
        'beta' => false,
        'hidden' => false,
        'disabled' => false,
    ],
    [
        'key' => 'pro',
        'name' => 'Titan Pro',
        'label' => 'Business Operations',
        'panel' => 'pro',
        'route' => '/pro',
        'icon' => 'briefcase',
        'category' => 'core',
        'enabled' => true,
        'locked' => false,
        'upgrade_required' => false,
        'coming_soon' => false,
        'beta' => false,
        'hidden' => false,
        'disabled' => false,
    ],
    [
        'key' => 'groundzero',
        'name' => 'Ground Zero',
        'label' => 'Daily Briefing',
        'panel' => 'groundzero',
        'route' => '/groundzero',
        'icon' => 'sun',
        'category' => 'core',
        'enabled' => true,
        'locked' => false,
        'upgrade_required' => false,
        'coming_soon' => false,
        'beta' => false,
        'hidden' => false,
        'disabled' => false,
    ],
    [
        'key' => 'titango',
        'name' => 'Titan Go',
        'label' => 'Field Operations',
        'panel' => 'titango',
        'route' => '/titango',
        'icon' => 'truck',
        'category' => 'operations',
        'enabled' => true,
        'locked' => false,
        'upgrade_required' => false,
        'coming_soon' => false,
        'beta' => false,
        'hidden' => false,
        'disabled' => false,
    ],
    [
        'key' => 'titanquotes',
        'name' => 'Titan Quotes',
        'label' => 'Quotes & Estimates',
        'panel' => 'titanquotes',
        'route' => '/titanquotes',
        'icon' => 'file-invoice',
        'category' => 'finance',
        'enabled' => true,
        'locked' => false,
        'upgrade_required' => false,
        'coming_soon' => false,
        'beta' => false,
        'hidden' => false,
        'disabled' => false,
        'category' => 'money',
    ],
    [
        'key' => 'zeropay',
        'name' => 'Zero Pay',
        'label' => 'Billing & Payments',
        'panel' => 'zeropay',
        'route' => '/zeropay',
        'icon' => 'credit-card',
        'category' => 'finance',
        'enabled' => true,
        'locked' => false,
        'upgrade_required' => false,
        'coming_soon' => false,
        'beta' => false,
        'hidden' => false,
        'disabled' => false,
        'category' => 'money',
    ],
    [
        'key' => 'titannexus',
        'name' => 'Titan Nexus',
        'label' => 'Marketing & CRM',
        'panel' => 'titannexus',
        'route' => '/titannexus',
        'icon' => 'paper-plane',
        'category' => 'growth',
        'enabled' => true,
        'locked' => false,
        'upgrade_required' => false,
        'coming_soon' => false,
        'beta' => false,
        'hidden' => false,
        'disabled' => false,
    ],
    [
        'key' => 'titanecho',
        'name' => 'Titan Echo',
        'label' => 'Communications',
        'panel' => 'titanecho',
        'route' => '/titanecho',
        'icon' => 'comments',
        'category' => 'communications',
        'enabled' => true,
        'locked' => false,
        'upgrade_required' => false,
        'coming_soon' => false,
        'beta' => false,
        'hidden' => false,
        'disabled' => false,
        'category' => 'support',
    ],
    [
        'key' => 'titanlocker',
        'name' => 'Titan Locker',
        'label' => 'Files & Storage',
        'panel' => 'titanlocker',
        'route' => '/titanlocker',
        'icon' => 'lock',
        'category' => 'storage',
        'enabled' => true,
        'locked' => false,
        'upgrade_required' => false,
        'coming_soon' => false,
        'beta' => false,
        'hidden' => false,
        'disabled' => false,
        'category' => 'assets',
    ],
    [
        'key' => 'titanmoney',
        'name' => 'Titan Money',
        'label' => 'Finance Reporting',
        'panel' => 'titanmoney',
        'route' => '/titanmoney',
        'icon' => 'dollar-sign',
        'category' => 'finance',
        'enabled' => true,
        'locked' => false,
        'upgrade_required' => false,
        'coming_soon' => false,
        'beta' => false,
        'hidden' => false,
        'disabled' => false,
        'category' => 'money',
    ],
    [
        'key' => 'titanpixel',
        'name' => 'Titan Pixel',
        'label' => 'Digital & Social',
        'panel' => 'titanpixel',
        'route' => '/titanpixel',
        'icon' => 'camera',
        'category' => 'growth',
        'enabled' => true,
        'locked' => false,
        'upgrade_required' => false,
        'coming_soon' => false,
        'beta' => false,
        'hidden' => false,
        'disabled' => false,
    ],
    [
        'key' => 'titansocial',
        'name' => 'Titan Social',
        'label' => 'Social & Marketing',
        'panel' => 'titansocial',
        'route' => '/titansocial',
        'icon' => 'users',
        'category' => 'growth',
        'enabled' => true,
        'locked' => false,
        'upgrade_required' => false,
        'coming_soon' => false,
        'beta' => false,
        'hidden' => false,
        'disabled' => false,
    ],
    [
        'key' => 'titanteam',
        'name' => 'Titan Team',
        'label' => 'Team Management',
        'panel' => 'titanteam',
        'route' => '/titanteam',
        'icon' => 'team',
        'category' => 'team',
        'enabled' => true,
        'locked' => false,
        'upgrade_required' => false,
        'coming_soon' => false,
        'beta' => false,
        'hidden' => false,
        'disabled' => false,
    ],
    [
        'key' => 'zeroissues',
        'name' => 'Zero Issues',
        'label' => 'Issue Tracking',
        'panel' => 'zeroissues',
        'route' => '/zeroissues',
        'icon' => 'bug',
        'category' => 'support',
        'enabled' => true,
        'locked' => false,
        'upgrade_required' => false,
        'coming_soon' => false,
        'beta' => false,
        'hidden' => false,
        'disabled' => false,
    ],
    [
        'key' => 'titanbookings',
        'name' => 'Titan Bookings',
        'label' => 'Bookings & Schedule',
        'panel' => 'titanbookings',
        'route' => '/titanbookings',
        'icon' => 'calendar',
        'category' => 'operations',
        'enabled' => true,
        'locked' => false,
        'upgrade_required' => false,
        'coming_soon' => false,
        'beta' => false,
        'hidden' => false,
        'disabled' => false,
    ],
    [
        'key' => 'titanpayroll',
        'name' => 'Titan Payroll',
        'label' => 'Payroll',
        'panel' => 'titanpayroll',
        'route' => '/titanpayroll',
        'icon' => 'wallet',
        'category' => 'finance',
        'enabled' => true,
        'locked' => false,
        'upgrade_required' => false,
        'coming_soon' => false,
        'beta' => false,
        'hidden' => false,
        'disabled' => false,
        'category' => 'money',
    ],
    [
        'key' => 'budgeting',
        'name' => 'Budgeting',
        'label' => 'Budgeting',
        'panel' => 'budgeting',
        'route' => '/budgeting',
        'icon' => 'chart-pie',
        'category' => 'finance',
        'enabled' => false,
        'locked' => false,
        'upgrade_required' => false,
        'coming_soon' => true,
        'beta' => false,
        'hidden' => false,
        'disabled' => true,
        'category' => 'money',
    ],
    [
        'key' => 'titanfleet',
        'name' => 'Titan Fleet',
        'label' => 'Fleet Management',
        'panel' => 'titanfleet',
        'route' => '/titanfleet',
        'icon' => 'truck',
        'category' => 'operations',
        'enabled' => false,
        'locked' => false,
        'upgrade_required' => false,
        'coming_soon' => true,
        'beta' => false,
        'hidden' => false,
        'disabled' => true,
    ],
    [
        'key' => 'routedispatchai',
        'name' => 'Route Dispatch AI',
        'label' => 'Route & Dispatch',
        'panel' => 'routedispatchai',
        'route' => '/routedispatchai',
        'icon' => 'map',
        'category' => 'operations',
        'enabled' => false,
        'locked' => false,
        'upgrade_required' => false,
        'coming_soon' => true,
        'beta' => false,
        'hidden' => false,
        'disabled' => true,
    ],
];