<?php

namespace App\Extensions\TitanCommand\System\Services;

use App\Extensions\TitanCommand\System\Models\Work\WorkJob;
use App\Extensions\TitanCommand\System\Models\Work\WorkJobEvidence;
use App\Extensions\TitanCommand\System\Models\Work\WorkJobEvent;
use App\Extensions\TitanCommand\System\Models\Work\WorkJobChecklist;
use App\Extensions\TitanCommand\System\Models\Work\WorkJobChecklistItem;

class ProofPackService
{
    public static function html(int $companyId, int $userId, int $jobId): string
    {
        $job = WorkJob::query()->where('company_id',$companyId)->where('user_id',$userId)->findOrFail($jobId);
        $events = WorkJobEvent::query()->where('company_id',$companyId)->where('user_id',$userId)->where('job_id',$jobId)->orderBy('id')->get();
        $evidence = WorkJobEvidence::query()->where('company_id',$companyId)->where('user_id',$userId)->where('job_id',$jobId)->orderBy('id')->get();
        $checklists = WorkJobChecklist::query()->where('company_id',$companyId)->where('user_id',$userId)->where('job_id',$jobId)->orderBy('id')->get();
        $checklistItems = WorkJobChecklistItem::query()->where('company_id',$companyId)->where('user_id',$userId)->where('job_id',$jobId)->orderBy('id')->get();

        $esc = fn($v) => htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8');

        $html = "<html><head><meta charset='utf-8'><title>Proof Pack</title>
        <style>
        body{font-family:DejaVu Sans, Arial, sans-serif; font-size:12px; color:#111}
        h1{font-size:18px;margin:0 0 8px}
        h2{font-size:14px;margin:18px 0 8px}
        table{width:100%;border-collapse:collapse}
        th,td{border:1px solid #ddd;padding:6px;vertical-align:top}
        th{background:#f6f6f6}
        .muted{color:#666}
        </style></head><body>";

        $html .= "<h1>Job Proof Pack</h1>";
        $html .= "<div><strong>Job #</strong> ".$esc($job->id)." <span class='muted'>(status: ".$esc($job->status).")</span></div>";
        $html .= "<div><strong>Title:</strong> ".$esc($job->title)."</div>";
        if ($job->description) $html .= "<div><strong>Description:</strong> ".$esc($job->description)."</div>";
        if ($job->scheduled_start) $html .= "<div><strong>Scheduled:</strong> ".$esc($job->scheduled_start)." - ".$esc($job->scheduled_end)."</div>";

        $html .= "<h2>Timeline</h2><table><tr><th>Type</th><th>At</th><th>Meta</th></tr>";
        foreach ($events as $e) {
            $meta = $e->meta_json ? json_encode($e->meta_json) : '';
            $html .= "<tr><td>".$esc($e->event_type)."</td><td>".$esc($e->created_at)."</td><td>".$esc($meta)."</td></tr>";
        }
        $html .= "</table>";

        $html .= "<h2>Checklists</h2>";
        foreach ($checklists as $c) {
            $html .= "<div><strong>".$esc($c->title)."</strong> <span class='muted'>(status: ".$esc($c->status).")</span></div>";
            $html .= "<table><tr><th>Item</th><th>Status</th><th>Notes</th></tr>";
            foreach ($checklistItems->where('checklist_id',$c->id) as $ci) {
                $html .= "<tr><td>".$esc($ci->label)."</td><td>".$esc($ci->status)."</td><td>".$esc($ci->notes ?? '')."</td></tr>";
            }
            $html .= "</table>";
        }

        $html .= "<h2>Evidence</h2><table><tr><th>Type</th><th>Label</th><th>Ref</th><th>Meta</th></tr>";
        foreach ($evidence as $ev) {
            $meta = $ev->meta_json ? json_encode($ev->meta_json) : '';
            $html .= "<tr><td>".$esc($ev->evidence_type)."</td><td>".$esc($ev->label)."</td><td>".$esc($ev->ref)."</td><td>".$esc($meta)."</td></tr>";
        }
        $html .= "</table>";

        $html .= "<div style='margin-top:18px' class='muted'>Generated by Titan Command</div>";
        $html .= "</body></html>";
        return $html;
    }

    public static function pdfBytes(string $html): ?string
    {
        if (class_exists('Dompdf\\Dompdf')) {
            $dompdf = new \Dompdf\Dompdf();
            $dompdf->loadHtml($html);
            $dompdf->setPaper('A4', 'portrait');
            $dompdf->render();
            return $dompdf->output();
        }
        return null;
    }
}
