-- Filtered support extract for dashboard hub integration
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;

CREATE TABLE `ext_chatbots` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `uuid` char(36) NOT NULL,
  `user_id` bigint(20) NOT NULL,
  `interaction_type` varchar(191) DEFAULT 'automatic_response',
  `title` varchar(191) NOT NULL,
  `bot_type` varchar(50) DEFAULT NULL,
  `bubble_message` text DEFAULT NULL,
  `welcome_message` text DEFAULT NULL,
  `connect_message` text DEFAULT NULL,
  `instructions` text DEFAULT NULL,
  `do_not_go_beyond_instructions` tinyint(1) NOT NULL DEFAULT 0,
  `language` varchar(191) DEFAULT NULL,
  `ai_model` varchar(191) NOT NULL,
  `ai_embedding_model` varchar(191) NOT NULL,
  `limit_per_minute` bigint(20) NOT NULL DEFAULT 2000,
  `show_pre_defined_questions` tinyint(1) NOT NULL DEFAULT 0,
  `pre_defined_questions` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`pre_defined_questions`)),
  `logo` longtext DEFAULT NULL COMMENT 'base 64',
  `avatar` varchar(191) DEFAULT NULL,
  `trigger_avatar_size` varchar(191) DEFAULT NULL,
  `trigger_background` varchar(191) DEFAULT NULL,
  `trigger_foreground` varchar(191) DEFAULT NULL,
  `color_mode` varchar(191) NOT NULL DEFAULT 'none',
  `color` varchar(191) DEFAULT '#017BE5',
  `show_logo` tinyint(1) NOT NULL DEFAULT 1,
  `show_date_and_time` tinyint(1) NOT NULL DEFAULT 1,
  `show_average_response_time` tinyint(1) NOT NULL DEFAULT 1,
  `position` varchar(191) NOT NULL DEFAULT 'right',
  `active` tinyint(1) NOT NULL DEFAULT 1,
  `footer_link` varchar(191) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `is_favorite` tinyint(1) NOT NULL DEFAULT 0,
  `is_demo` tinyint(1) NOT NULL DEFAULT 0,
  `is_email_collect` tinyint(1) NOT NULL DEFAULT 1,
  `is_contact` tinyint(1) NOT NULL DEFAULT 1,
  `is_attachment` tinyint(1) NOT NULL DEFAULT 1,
  `is_emoji` tinyint(1) NOT NULL DEFAULT 1,
  `is_articles` tinyint(1) NOT NULL DEFAULT 1,
  `is_links` tinyint(1) NOT NULL DEFAULT 1,
  `whatsapp_link` varchar(191) DEFAULT NULL,
  `telegram_link` varchar(191) DEFAULT NULL,
  `watch_product_tour_link` varchar(191) DEFAULT NULL,
  `header_bg_type` varchar(191) DEFAULT 'color',
  `header_bg_color` varchar(191) DEFAULT NULL,
  `header_bg_gradient` varchar(191) DEFAULT NULL,
  `header_bg_image` varchar(191) DEFAULT NULL,
  `human_agent_conditions` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`human_agent_conditions`)),
  `channel_settings` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`channel_settings`)),
  `nav_schema` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`nav_schema`)),
  `engine_permissions` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`engine_permissions`)),
  `theme_preset` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`theme_preset`)),
  `rules` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`rules`)),
  `tools_enabled` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'JSON array of enabled tools' CHECK (json_valid(`tools_enabled`)),
  `tool_permissions` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'Per-tool permissions and settings' CHECK (json_valid(`tool_permissions`))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `ext_chatbots` (`id`, `uuid`, `user_id`, `interaction_type`, `title`, `bot_type`, `bubble_message`, `welcome_message`, `connect_message`, `instructions`, `do_not_go_beyond_instructions`, `language`, `ai_model`, `ai_embedding_model`, `limit_per_minute`, `show_pre_defined_questions`, `pre_defined_questions`, `logo`, `avatar`, `trigger_avatar_size`, `trigger_background`, `trigger_foreground`, `color_mode`, `color`, `show_logo`, `show_date_and_time`, `show_average_response_time`, `position`, `active`, `footer_link`, `created_at`, `updated_at`, `is_favorite`, `is_demo`, `is_email_collect`, `is_contact`, `is_attachment`, `is_emoji`, `is_articles`, `is_links`, `whatsapp_link`, `telegram_link`, `watch_product_tour_link`, `header_bg_type`, `header_bg_color`, `header_bg_gradient`, `header_bg_image`, `human_agent_conditions`, `channel_settings`, `nav_schema`, `engine_permissions`, `theme_preset`, `rules`, `tools_enabled`, `tool_permissions`) VALUES

(1, '01813561-2294-11f1-aebc-00163e2cc358', 1, 'automatic_response', 'Customer Assistant', 'customer_multi_mode', 'Hi! 👋 Need help?', 'Welcome! I can help you book, get a quote, or answer questions.', 'Connecting to support team...', 'You are a customer service assistant for a service business.\r\n\r\nIMPORTANT: Auto-detect customer intent and switch modes:\r\n\r\n1. BOOKING MODE - When customer says: \"book\", \"schedule\", \"appointment\", \"I need\"\r\n   - Ask for date/time\r\n   - Confirm address\r\n   - Create booking\r\n   - Send confirmation\r\n\r\n2. QUOTE MODE - When customer asks: \"price\", \"cost\", \"how much\", \"quote\"\r\n   - Ask about scope (size, complexity)\r\n   - Calculate price\r\n   - Send quote link\r\n   - Mark as interested lead\r\n\r\n3. FAQ MODE - When customer asks: \"question\", \"how\", \"what\", \"do you\", \"policy\"\r\n   - Answer from knowledge base\r\n   - Provide helpful info\r\n   - Link to resources\r\n\r\n4. COMPLAINT MODE - When customer is upset: \"bad\", \"poor\", \"complaint\", \"refund\", \"upset\", \"disappointed\"\r\n   - Acknowledge problem\r\n   - Offer solution (re-do, credit, refund)\r\n   - Escalate to manager immediately\r\n\r\n5. LEAD QUALIFY MODE - When unsure if customer fits: \"area\", \"location\", \"neighborhood\", \"city\"\r\n   - Confirm service zone\r\n   - Verify service available\r\n   - Check budget fit\r\n\r\n6. JOB TRACKING MODE - When customer asks: \"where\", \"technician\", \"status\", \"ETA\", \"arrive\"\r\n   - Show job status\r\n   - Display tech location/ETA\r\n   - Provide tech profile\r\n\r\nDefault: Be helpful, professional, cheerful. Escalate complaints immediately.\r\nNever go beyond these instructions. If unsure, escalate to human agent.', 0, 'en', 'gpt-4-turbo', 'text-embedding-3-large', 2000, 1, '{\"booking\": \"I need to book a service\", \"quote\": \"How much does it cost?\", \"faq\": \"Do you offer window cleaning?\", \"complaint\": \"I had a bad experience\", \"qualify\": \"Can you service my area?\", \"tracking\": \"Where is my technician?\"}', NULL, '5', '40px', '#ffffff', '#01BE56', 'light', '#01BE56', 1, 1, 1, 'bottom-right', 1, NULL, '2026-03-18 06:30:50', '2026-03-18 06:30:50', 0, 0, 1, 1, 1, 1, 1, 1, NULL, NULL, NULL, 'color', '#01BE56', NULL, NULL, NULL, '{\"sms\": true, \"email\": true, \"whatsapp\": true}', '{\"show_search\": true, \"show_categories\": true}', '{\"tools\": [\"knowledge_base\", \"embedding_search\", \"web_scrap\"]}', '{\"primary_color\": \"#01BE56\", \"font_family\": \"Inter\"}', '{\"escalate_on_complaint\": true, \"escalate_on_timeout\": true}', NULL, NULL),
,
(2, '5b5c00b5-229a-11f1-aebc-00163e2cc358', 1, 'automatic_response', 'Customer Assistant', 'customer_multi_mode', 'Hi! 👋 Need help?', 'Welcome to our service! I can help you book, get a quote, or answer questions.', 'Connecting to support team...', 'You are a customer service assistant for a service business (cleaning, plumbing, landscaping, etc).\n\nYou have these modes, activated by customer intent:\n\n1. BOOKING MODE - When customer says \"book\", \"schedule\", \"appointment\"\n   - Ask for service date\n   - Confirm time slot\n   - Collect address\n   - Create booking\n\n2. QUOTE MODE - When customer asks \"how much\", \"price\", \"cost\"\n   - Ask about service scope (size, complexity)\n   - Calculate price with modifiers\n   - Send quote link\n   - Track interested leads\n\n3. FAQ MODE - When customer asks general questions\n   - Answer from knowledge base\n   - Provide helpful information\n   - Direct to relevant resources\n\n4. COMPLAINT MODE - When customer is unhappy\n   - Acknowledge issue\n   - Offer solution (re-do, credit, refund)\n   - Escalate to manager if needed\n\n5. LEAD QUALIFICATION MODE - When unsure if customer fits\n   - Confirm service area\n   - Verify service type available\n   - Check budget compatibility\n\n6. JOB TRACKING MODE - When customer asks \"where is my tech\"\n   - Show current job status\n   - Display technician ETA\n   - Show tech profile\n\nDefault: Be helpful, professional, cheerful. If unsure, escalate to human agent.', 0, 'en', 'gpt-4-turbo', 'text-embedding-3-large', 2000, 1, '{\"mode_1\": \"I need to book a cleaning service\", \"mode_2\": \"How much does a service cost?\", \"mode_3\": \"Do you offer window cleaning?\", \"mode_4\": \"I\'m not happy with my last service\", \"mode_5\": \"Can you service my area?\", \"mode_6\": \"Where is my technician?\"}', NULL, '5', '40px', '#ffffff', '#01BE56', 'light', '#017BE5', 1, 1, 1, 'bottom-right', 1, NULL, '2026-03-18 07:16:17', '2026-03-18 07:16:17', 0, 0, 1, 1, 1, 1, 1, 1, NULL, NULL, NULL, 'color', '#01BE56', NULL, NULL, NULL, '{\"sms\": true, \"email\": true, \"whatsapp\": true}', '{\"show_search\": true, \"show_categories\": true}', '{\"tools\": [\"knowledge_base\", \"embedding_search\", \"web_scrap\"]}', '{\"primary_color\": \"#01BE56\", \"font_family\": \"Inter\"}', '{\"require_email\": true, \"require_phone\": true, \"escalate_on_complaint\": true, \"escalate_on_timeout\": true}', NULL, NULL),
,
(3, '3f21080b-229b-11f1-aebc-00163e2cc358', 1, 'automatic_response', 'Booking Bot', 'customer_booking', 'Book your next appointment', 'Hi! I can help you schedule your appointment. What date and time work best for you?', NULL, 'You are a booking specialist. ONLY help customers schedule appointments. Do NOT discuss pricing, complaints, or other topics. Always confirm booking details.', 0, 'en', 'gpt-4-turbo', 'text-embedding-3-large', 2000, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'none', '#3B82F6', 1, 1, 1, 'right', 1, NULL, '2026-03-18 07:22:39', '2026-03-18 07:22:39', 0, 0, 1, 1, 1, 1, 1, 1, NULL, NULL, NULL, 'color', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[\"knowledge_base\", \"embedding_search\"]', '{\"knowledge_base\": {\"risk_level\": \"LOW\", \"requires_confirmation\": false, \"scope\": \"service_areas_only\"}, \"embedding_search\": {\"risk_level\": \"LOW\", \"requires_confirmation\": false}}'),
,
(4, '3f21b6d1-229b-11f1-aebc-00163e2cc358', 1, 'automatic_response', 'Quote Bot', 'customer_quote', 'Get an instant quote', 'Tell me about your project and I\'ll provide a competitive quote right away.', NULL, 'You are a pricing expert. ONLY provide quotes based on service type and scope. Do NOT discuss booking or complaints. Keep quotes accurate and professional.', 0, 'en', 'gpt-4-turbo', 'text-embedding-3-large', 2000, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'none', '#10B981', 1, 1, 1, 'right', 1, NULL, '2026-03-18 07:22:39', '2026-03-18 07:22:39', 0, 0, 1, 1, 1, 1, 1, 1, NULL, NULL, NULL, 'color', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[\"knowledge_base\", \"embedding_search\"]', '{\"knowledge_base\": {\"risk_level\": \"LOW\", \"requires_confirmation\": false, \"scope\": \"pricing_only\"}, \"embedding_search\": {\"risk_level\": \"LOW\", \"requires_confirmation\": false}}'),
,
(5, '3f2297ec-229b-11f1-aebc-00163e2cc358', 1, 'automatic_response', 'FAQ Bot', 'customer_faq', 'Ask us anything', 'Welcome! Ask any questions about our services. If I can\'t help, I\'ll connect you with a specialist.', NULL, 'You are a helpful FAQ assistant. Answer general questions about services. Route complex requests to appropriate specialist (booking, pricing, or complaint handler).', 0, 'en', 'gpt-4-turbo', 'text-embedding-3-large', 2000, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'none', '#F59E0B', 1, 1, 1, 'right', 1, NULL, '2026-03-18 07:22:39', '2026-03-18 07:22:39', 0, 0, 1, 1, 1, 1, 1, 1, NULL, NULL, NULL, 'color', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[\"knowledge_base\", \"embedding_search\"]', '{\"knowledge_base\": {\"risk_level\": \"LOW\", \"requires_confirmation\": false, \"scope\": \"all\"}, \"embedding_search\": {\"risk_level\": \"LOW\", \"requires_confirmation\": false}}'),
,
(6, '3f233e42-229b-11f1-aebc-00163e2cc358', 1, 'automatic_response', 'Complaint Handler', 'customer_complaint', 'We\'re here to help', 'I\'m sorry you\'re experiencing an issue. Tell me what happened and I\'ll work to resolve it immediately.', NULL, 'You are a complaint resolution specialist. Listen empathetically. Offer solutions. Escalate to manager if needed. Document all complaint details.', 0, 'en', 'gpt-4-turbo', 'text-embedding-3-large', 2000, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'none', '#EF4444', 1, 1, 1, 'right', 1, NULL, '2026-03-18 07:22:39', '2026-03-18 07:22:39', 0, 0, 1, 1, 1, 1, 1, 1, NULL, NULL, NULL, 'color', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[\"knowledge_base\", \"embedding_search\", \"web_scrap\"]', '{\"knowledge_base\": {\"risk_level\": \"LOW\", \"requires_confirmation\": false}, \"embedding_search\": {\"risk_level\": \"LOW\", \"requires_confirmation\": false}, \"web_scrap\": {\"risk_level\": \"MEDIUM\", \"requires_confirmation\": true}}'),
,
(7, '3f23eb38-229b-11f1-aebc-00163e2cc358', 1, 'automatic_response', 'Lead Qualifier', 'customer_qualify', 'Tell us about your project', 'Hi! To ensure we\'re the right fit, let me ask a few quick questions about your project.', NULL, 'Qualify leads by area coverage and service scope. If out of area, apologize professionally. If budget is unclear, offer to escalate to manager.', 0, 'en', 'gpt-4-turbo', 'text-embedding-3-large', 2000, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'none', '#8B5CF6', 1, 1, 1, 'right', 1, NULL, '2026-03-18 07:22:39', '2026-03-18 07:22:39', 0, 0, 1, 1, 1, 1, 1, 1, NULL, NULL, NULL, 'color', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[\"knowledge_base\", \"embedding_search\"]', '{\"knowledge_base\": {\"risk_level\": \"LOW\", \"requires_confirmation\": false, \"scope\": \"areas_services\"}, \"embedding_search\": {\"risk_level\": \"LOW\", \"requires_confirmation\": false}}'),
,
(8, '3f25049e-229b-11f1-aebc-00163e2cc358', 1, 'automatic_response', 'Job Tracker', 'customer_tracking', 'Track your job in real-time', 'Enter your job ID and I\'ll show you live progress, team location, and ETA.', NULL, 'Track job status. Show real-time progress and ETA. Be transparent about delays. Offer to escalate if customer wants to reschedule.', 0, 'en', 'gpt-4-turbo', 'text-embedding-3-large', 2000, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'none', '#EC4899', 1, 1, 1, 'right', 1, NULL, '2026-03-18 07:22:39', '2026-03-18 07:22:39', 0, 0, 1, 1, 1, 1, 1, 1, NULL, NULL, NULL, 'color', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[\"knowledge_base\", \"embedding_search\"]', '{\"knowledge_base\": {\"risk_level\": \"LOW\", \"requires_confirmation\": false, \"scope\": \"parking_tips\"}, \"embedding_search\": {\"risk_level\": \"LOW\", \"requires_confirmation\": false}}');

COMMIT;
